### ISSUE TITLE
Support HIP

### ISSUE THREAD

**Issue by okuta** [cupy/cupy#1117]
I sent total PR #1094 . 
I will send split PR as following list.
- [x] Fix setup.py (#1121 , etc.)
- [x] Support compiler on HIP (#1094)
- [x] Fix header files (#1094)
- [x] Use fmin and fmax for HIP environment #1116
- [ ] BLAS
- [x] RAND (#1094)
- [ ] SPARSE
- [ ] SOLVER
- [ ] DNN
- [x] CI
- [x] rocThrust (#2666)

**Comment by adityaatluri** [comment]
Hi,
Great work! Would like to talk more about rocm support. Can you share your email id? @gstoner

**Comment by kazulittlefox** [comment]
Hi.
Can i help for your testing codes before merging pull request ?

**Comment by okuta** [comment]
Thanks.
At first, I plan to fix some base functions. For example, `setup.py` and `compiler.py`.
I would like you to cooperate with the test after merging these PRs.

**Comment by kazulittlefox** [comment]
>Okuta.
OK, I'll try them.

**Comment by mihirparadkar** [comment]
This site (https://gpueater.com/) provides virtual servers with AMD graphics cards (and images that come with ROCm installed). Perhaps those could also be useful for testing purposes.

**Comment by leofang** [comment]
Related:
- [ ] FFT (#3892)
- [ ] CUB (#3893)

**Comment by leofang** [comment]
@okuta @emcastillo I think this issue can be closed. The only component we haven't covered is hipSPARSE/rocSPARSE, for which we can issue a separate ticket to track.
