### ISSUE TITLE
Jenkins test failure

### ISSUE THREAD

**Issue by niboshi** [cupy/cupy#2370]
https://jenkins.preferred.jp/job/chainer/job/cupy_pr/239/TEST=cupy-py3,label=mn1-p100/#showFailuresLink

- [x] DeprecationWarning
  - (#2394, v6: #2401)
  - (#2385, v6: #2395)
- [x] `tests.cupy_tests.core_tests.test_ndarray_elementwise_op.TestArrayElementwiseOp` (#2376, v6: #2378)
- ~`tests.cupy_tests.random_tests.test_generator.TestRandomSampleDistrib` (@niboshi)~
- [x] `tests.cupy_tests.random_tests.test_distributions.TestDistributionsPower` (#2375, v6: #2380)
- [x] `tests.cupy_tests.fft_tests.test_fft.TestFft` (#2361, v6: #2381)

**Comment by niboshi** [comment]
I confirmed `TestDistributionsPower` failure is only from NumPy 1.17, but `TestRandomSampleDistrib` could not be replicated. Perhaps it's just a stochastic error?
Indeed it's not in the failure list of this Jenkins build: https://jenkins.preferred.jp/job/chainer/job/cupy_pr/240/TEST=cupy-py3,label=mn1-p100/#showFailuresLink

**Comment by asi1024** [comment]
I confirmed `DeprecationWarning`s are only from NumPy 1.17.
