### ISSUE TITLE
Recent refurbishment of `RawKernel`

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2450]
This is simply a meta-issue keeping track of recent changes / ongoing efforts made to (or built on top of) `RawKernel`, so that the progress in those scattered PRs can be monitored in one place.
- [x] Support texture memory (#2432)
- [x] Support separate compilation (for dynamic parallelism, etc) (#2426)
- [x] Support `nvcc` backend (#1941)
- [x] ~~Document the usage of complex-valued arrays in `RawKernel` (#1866)~~ 
**UPDATE:** superseded by #2551
- [x] Add `RawModule` (#2389)
- [x] Get & set kernel attributes (#2369)
- [x] Support constant memory (#2510)
- [x] Support `cuComplex.h` (#2551)

Somewhat relevant:
- [x] Add occupancy driver APIs (#2424): The `RawKernel`'s pointer can be passed to the driver API for obtaining the occupancy estimation.

**Comment by leofang** [comment]
After the pending PRs are merged, I expect that these changes together should offer painless migration experience from PyCUDA to CuPy :sunglasses:

**Comment by leofang** [comment]
> After the pending PRs are merged, I expect that these changes together should offer painless migration experience from PyCUDA to CuPy 😎

Success story: https://github.com/cupy/cupy/pull/2432#issuecomment-534268065

**Comment by grlee77** [comment]
One other feature related to `RawKernel` that would be good to document is a the use of dynamically allocated shared memory. It looks like the kernel launch in CuPy already supports a `shared_mem` kwarg, but this does not appear to be documented. I assume that with this argument it should be possible to do things like the dynamic shared memory example in
https://devblogs.nvidia.com/using-shared-memory-cuda-cc/ ? Do you happen to have already tried this and know whether it works?

**Comment by leofang** [comment]
@grlee77 Yes, I've used it. This is why we needed #2369 🙂 In part of our code we needed to enlarge the shared memory maximum. 

For the example you linked, a CuPy counterpart looks like this:
```python
import cupy as cp

code = r'''
extern "C"{
__global__ void dynamicReverse(int *d, int n)
{
  extern __shared__ int s[];
  int t = threadIdx.x;
  int tr = n-t-1;
  s[t] = d[t];
  __syncthreads();
  d[t] = s[tr];
}
}
'''

n = 64
a = cp.arange(n, dtype=cp.int32)
r = cp.arange(n-1, -1, -1, dtype=cp.int32)

ker = cp.RawKernel(code, 'dynamicReverse')
ker((1,), (n,), (a, n), shared_mem=n*a.dtype.itemsize)
assert (a == r).all()
```
For this case it's hard to ask beyond the default shared memory limit (=49152 bytes on my GPU), as the maximum block size is only 1024. 

I think `RawKernel`'s docstring does document this usage, see [here](https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.RawKernel.html#cupy.RawKernel.__call__). But if you think showing how to use `shared_mem` in the tutorial is a good idea, I can create a PR using this example.

Thanks.

**Comment by leofang** [comment]
@kmaehashi I wonder if relevant PRs involved in this meta-issue can be merged before the official v7.0 release? Does this fit the CuPy team's schedule and agenda?

**Comment by leofang** [comment]
(Updated the TODO list.)

**Comment by leofang** [comment]
> After the pending PRs are merged, I expect that these changes together should offer painless migration experience from PyCUDA to CuPy 😎

Another success story: https://github.com/cupy/cupy/pull/2432#issuecomment-543193359.

**Comment by leofang** [comment]
(Added #2551 to the TODO list.)

**Comment by leofang** [comment]
Thanks to everyone @emcastillo @kmaehashi @niboshi @asi1024 @sjperkins @grlee77 for helps and comments! It's been a long journey and finally we have all enhancements added.
