### ISSUE TITLE
Discussion for possible enhancements of the new CUB support

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2519]
With the great effort by @anaruse in #2090, I've seen encouraging performance boosts. Below is a list of possible improvements I can think of, either for offering extensive support or for enabling even more boost. I am interested in knowing what I've missed or misunderstood.
- [x] Support complex numbers (#2538)
- [x] Allow using CUDA streams: (#2555)

if users set up a context manager like this
```python
with stream:
    arr.sum()
    # do other stuff
```
The non-default `stream` should be honored. All of the CUB functions introduced in #2090 support an optional stream argument. We just need to pick up the current stream pointer during setup and modify the wrappers.
- [x] ~~Change the CUB wrappers from `def` to `cdef` or `cpdef`:~~ **(UPDATE: see https://github.com/cupy/cupy/issues/2519#issuecomment-538205781)**

~~currently they are all Python `def` functions. Could be be beneficial for performance. In particular, if we don't want to expose those wrappers to end users, `cdef` would be a nice choice.~~
- [x] Support batch reduction for contiguous arrays (#2562): 

currently only a full reduction is supported, but if a reduction over the last axes of a contiguous array of shape, say, `(X, Y, Z)`,  is needed, this seems possible with a naive loop over the remaining axes. In other words, in this case we can use CUB to do `arr.sum(axis=2)` or `arr.sum(axis=(1,2))`, assuming `arr` is C contiguous. This resembles the current treatment of `PlanNd` in the FFT module.

- [ ] Document how to enable CUB support if built from source: Need to set `CUB_PATH` and `CUB_DISABLED`. 
-> could be avoided if the CUB source code is bundled (#2584)
- [x] Support `argmin` and `argmax` (#2596 enables a global (no `axis`) search)
- [x] Support half-precision floating points (#2600)
- [x] Support F-contiguous arrays (#2682)
- [x] Support sparse matrix operation (#2698)
- [x] Honor the `keepdims` argument (#2725)

~~Question: (from https://github.com/cupy/cupy/pull/2508#issuecomment-536368493): is Jenkins configured to test CUB functionalities?~~ ***UPDATE***: No, see https://github.com/cupy/cupy/pull/2538#issuecomment-543507886.

**Comment by leofang** [comment]
> * Support batch reduction for contiguous arrays: currently only a full reduction is supported, but if a reduction over the last axes of a contiguous array of shape, say, `(X, Y, Z)`,  is needed, this seems possible with a naive loop over the remaining axes. In other words, in this case we can use CUB to do `arr.sum(axis=2)` or `arr.sum(axis=(1,2))`, assuming `arr` is C contiguous. This resembles the current treatment of `PlanNd` in the FFT module.

Could also be useful? http://nvlabs.github.io/cub/structcub_1_1_device_segmented_reduce.html

**Comment by grlee77** [comment]
Agreed that enhancements to add segmented reductions and/or looping to support batch reduction would be great. 

Functions for `argmin` and `argmax` reductions are also available in CUB and could be added.
http://nvlabs.github.io/cub/structcub_1_1_device_reduce.html#a6b35963e90120b6d2c76a6068b0340a9

**Comment by grlee77** [comment]
See also #2517 which extends support for the existing 1d reductions to include other valid `axis` argument and `keepdims` combinations

**Comment by leofang** [comment]
Oh cool. You move so fast @grlee77! In #2508 I enabled support of complex numbers. I wonder if we should just combine the two PRs into one. Some conflicts need to be resolved either way.

**Comment by grlee77** [comment]
> Oh cool. You move so fast @grlee77! In #2508 I enabled support of complex numbers. I wonder if we should just combine the two PRs into one. Some conflicts need to be resolved either way.

I think it was just coincidence that I happened to be working on `linalg.norm` earlier this week :). I was initially defining simple `ReductionKernels` for various norms, but then found that relying on CUB would be much faster in cases where it can be used. I don't mind rebasing after #2508 is merged (or just rebasing on it now if you prefer to go that way).

**Comment by leofang** [comment]
> I think it was just coincidence that I happened to be working on `linalg.norm` earlier this week :)

I see, I thought you were looking into #2516 already 😆 

> I was initially defining simple `ReductionKernels` for various norms, but then found that relying on CUB would be much faster in cases where it can be used. 

Interesting. I suppose at some point we could even rewrite the logic in `ReductionKernel` based on CUB!

> I don't mind rebasing after #2508 is merged (or just rebasing on it now if you prefer to go that way).

Well, now that I think about it, I guess the complex numbers can wait after your #2517, which is a more fundamental work.

**Comment by leofang** [comment]
> * Change the CUB wrappers from `def` to `cdef` or `cpdef`:

Just tried this, no difference in timing. I wonder why...

**Comment by anaruse** [comment]
Just FYI. You can also speedup reduction operations using cuTENSOR.
https://pspringer.gitlab-master-pages.nvidia.com/cuTensor/sphinx/api/cutensor.html#cutensorreduction
`cutensorReduction` is implemented in cuTENSOR 0.2 and cuTENSOR 0.2 will be available in CuPy once theis PR is merged (https://github.com/cupy/cupy/pull/2341)

**Comment by grlee77** [comment]
There was also related discussion about using `cudnnReduceTensor` in #2294. However, it seems **cuDNN** does not have complex-valued support either.  **cuTENSOR** does support complex-valued tensors and also seems to support reduction over specific axes of n-d arrays.

**Comment by leofang** [comment]
@grlee77 I'm preparing a PR for native support of complex numbers in CUB, and I'll abandon #2508 then. I see a very promising performance (of course). Can you help me test it later?

**Comment by anaruse** [comment]
> Do you know if cuTENSOR will be bundled with an upcoming CUDA Toolkit release (like cuSPARSE, cuFFT, etc. are now) or will it remain a separate library?

It will be a separate library like cuDNN.

> edit:: Just wanted to confirm that I was able to obtain cuTENSOR via the early access link I posted in this comment

Yes, you can download cuTENSOR EA via the link once you join NVIDIA Developer Program.
https://developer.nvidia.com/developer-program/signup

**Comment by leofang** [comment]
@anaruse, I have a quick question: Since CUB is header-only, are we legally allowed to distribute it along with CuPy's source code (and wheels) on PyPI? Bundling it would be more convenient for users.

**Comment by leofang** [comment]
By the way, the last update time for CUB was Feb 2018? @anaruse do you know why? Is it because CUB is absorbed into Thrust?

**Comment by anaruse** [comment]
> are we legally allowed to distribute it along with CuPy's source code (and wheels) on PyPI?

I'm not a legal person, so I'm not so sure, but it would be OK as long as distribution way conforms to BSD-3-Clause License.
https://github.com/NVlabs/cub/blob/1.8.0/LICENSE.TXT

**Comment by anaruse** [comment]
> Is it because CUB is absorbed into Thrust?

CUB is internally used by Thrust (see /usr/local/cuda/include/thrust/system/cuda/detail/cub), but it does not mean that CUB is absorbed into Thrust.

**Comment by leofang** [comment]
Thanks @anaruse for both answers! Sounds like we could just cherry-pick the needed CUB header files and include them in CuPy (along with the license file of course), very much like how Thrust was included. Since v1.8.0 is quite stable for a while, I suggest to pin at this version.

The next question would be if we wanna enable CUB reductions by default.

**Comment by leofang** [comment]
> Support batch reduction for contiguous arrays:
> 
> currently only a full reduction is supported, but if a reduction over the last axes of a contiguous array of shape, say, `(X, Y, Z)`, is needed, this seems possible with a naive loop over the remaining axes. In other words, in this case we can use CUB to do `arr.sum(axis=2)` or `arr.sum(axis=(1,2))`, assuming `arr` is C contiguous. This resembles the current treatment of `PlanNd` in the FFT module.

I got this working in https://github.com/leofang/cupy/tree/cub_enhance with CUB's `device_segmented_reduce`. The idea is to do a device-device copy to make reduced axes be contiguous. But, the performance numbers are not uniformly better across all test combinations (tried different `axis` setup for a `ndim=3` array). Looking into this now.

If anyone is interested, please feel free to comment / diagnose / improve before I create a PR. I feel some decision making (like applying this to certain cases instead of making it a generic solution?) has to be done.

**Comment by leofang** [comment]
> I got this working in https://github.com/leofang/cupy/tree/cub_enhance with CUB's `device_segmented_reduce`. The idea is to do a device-device copy via transpose to make reduced axes be contiguous. But, the performance numbers are not uniformly better across all test combinations (tried different `axis` setup for a `ndim=3` array). Looking into this now. Most likely the copy is slowing things down (to contrast, CuPy's reduction kernel doesn't do any copy).
> 
> If anyone is interested, please feel free to comment / diagnose / improve before I create a PR. I feel some decision making (like applying this to certain cases instead of making it a generic solution?) has to be done.

See #2562.

**Comment by leofang** [comment]
> Sounds like we could just cherry-pick the needed CUB header files and include them in CuPy (along with the license file of course), very much like how Thrust was included. Since v1.8.0 is quite stable for a while, I suggest to pin at this version.

Bundling CUB is attempted in #2584.

**Comment by leofang** [comment]
`argmin()` and `argmax()` are supported in #2596.

**Comment by grlee77** [comment]
I implemented [cub::DeviceSpmv::CsrMV](https://nvlabs.github.io/cub/structcub_1_1_device_spmv.html) for CuPy today and it seems to be 3-4 times faster than the cuSPARSE-based implementation in my initial testing. I will make a PR shortly.

**Comment by leofang** [comment]
Cool, I completely overlooked that section in the CUB documentation! I wonder why doesn't CUB support other kinds of sparse matrix operations...

**Comment by grlee77** [comment]
As documented in https://github.com/cupy/cupy/pull/2725#issuecomment-559879307, we could also use CUB to accelerate `mean` (which is also used internally by `std` and `var`)

**Comment by leofang** [comment]
I am closing this meta-issue, as most of the listed tasks are completed except for the source-tree bundling (#2584) and the tests (#2598). Thanks to everyone for making all these improvements! It's been a not-so-short, perhaps a bit bumpy journey since @anaruse added the initial support. 🙂
