### ISSUE TITLE
Support NumPy 1.18

### ISSUE THREAD

**Issue by toslunar** [cupy/cupy#2991]
- non-compatible changes
  - [x] #2852 [`np.can_cast(np.uint64, np.timedelta64, casting='safe')` is now `False`](https://numpy.org/devdocs/release/1.18.0-notes.html#np-can-cast-np-uint64-np-timedelta64-casting-safe-is-now-false)
  - [x] #2883 error message in `numpy.testing`
  - [x] #2974 `isscalar(num)` -> `isscalar(element)`
  - [x] #2975 `step` returned by `linspace(..., retstep=True)`
- [expired deprecations](https://numpy.org/devdocs/release/1.18.0-notes.html#expired-deprecations)
  - [x] #2992 "The deprecation of `expand_dims` out-of-range axes in 1.13.0 has expired. ([gh-14051](https://github.com/numpy/numpy/pull/14051))"
- [ ] #3005 cupy documentation
