### ISSUE TITLE
cupy.sparse

### ISSUE THREAD

**Issue by unnonouno** [cupy/cupy#36]
I want to implement sparse matrix named `cupy.sparse` whose interface is same as `scipy.sparse` using cuSparse.
I investigated specification of cuSparse.
- Many sparse representations exist such as csr, csc and coo. And all of them are compatible with `scipy.sparse`.
- Most APIs are provided for only csr representation.
- Conversion APIs between csr and other types of formats such as csc and coo are provided.
- `scipy.sparse` has no special implementation except for `csc_matrix`. It convert matrixes to csc format and call its implementation.
- We need to use `__array_priority__` attribute to control calling operator method such as `__add__`.

Todo:
- [x] cuSparse thin-wrapper (#39)
- [x] `spmatrix`: base class of all sparse matrixes (https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.sparse.spmatrix.html#scipy.sparse.spmatrix) (#40)
- [x] `csr_matrix`: most basic sparse matrix in cuSparse (https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.sparse.csr_matrix.html) 
  - All APIs are implemented in this class. All other types of sparse matrixes are converted to csr and call methods in csr (#226).
- [x] `csc_matrix`: transpose of csr (https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.sparse.csc_matrix.html#scipy.sparse.csc_matrix) (#226)
- [x] `coo_matrix`: it is easier to make (https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.sparse.coo_matrix.html#scipy.sparse.coo_matrix) (#234)
- [x] conversion APIs (#235)
- [x] getitem
  - [x] single element (`int, int`) (#240)
  - [x] major dimension (`int`) (#301)
  - [x] ellipsis (#302)
  - [x] `slice`
- [x] copy (#236)
- [x] elementwise ufuncs (#226, #234)
- [x] `__add__` and `__sub__`
  - [x] for `csr` and `csc` (#238)
  - [x] for `coo` (#401)
- [x] `dot` and `__mul__`
  - [x] `csr_matrix.__mul__` (#239)
  - [x] `__rmul__` (#300)
  - [x] `__dot__` (equivalent to `__mul__`, #351, #352)
  - [x] `__mul__` for other sparse matrices (#401)
- [x] dia_matrix (#313, #320, #321)
- [x] construction methods
  - [x] eye (#358)
  - [x] spdiags
- [x] dense to sparse (#335)
- [x] sum_duplicates (#326, #371)
- [x] document (#303)

**Comment by unnonouno** [comment]
I implemented all features i planned to make in the first version. I'll close this issue.

**Comment by Daulbaev** [comment]
Thank you for developing such an important tool!
Could you please help me?
I have three sparse matrices A, B and C, such that C.shape == (A.dot(B)).shape. 
I want to multiply A.dot(B) and then remove elements which are equal to zero in C. 
For dense matrices it looks like
`res = A.dot(B)
res[C == 0] = 0`,
but I don't know how to implement this function in cupy.sparse.

**Comment by lakehanne** [comment]
If you already have a `scipy.sparse` matrix, doing `cp.asarray(scipy_sparse_matrix)` does not move the array to the device. What is the way to move sparse matrices back and forth from host to memory?

**Comment by kmaehashi** [comment]
@lakehanne  e.g.

Host-to-GPU: `x = cupy.sparse.csr_matrix(scipy_sparse_matrix)` 
GPU-to-Host: `scipy_sparse_matrix = x.get()`

**Comment by lakehanne** [comment]
@kmaehashi thanks!
