### ISSUE TITLE
Support CUDA 11.3

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5095]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read [CUDA Release Notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html).
- [x] Update CUDA driver in Linux (Jenkins) / Windows (FlexCI) test infrastructure (ask @kmaehashi). -> ongoing
- [x] Update chainer-test to test the CUDA version. https://github.com/chainer/chainer-test/pull/658
- [x] Update compute capability support.
  - [x] Check [NVRTC Reference (--gpu-architecture option)](https://docs.nvidia.com/cuda/nvrtc/index.html#group__options) and change the maximum value of supported compute capability defined in [cupy/cuda/compiler.py](https://github.com/cupy/cupy/blob/master/cupy/cuda/compiler.py) (`_nvrtc_max_compute_capability`) if needed. -> *no changes needed*
  - [x] Check [NVCC Reference (--generate-code)](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-steering-gpu-code-generation-generate-code) and change the list of architectures in [cupy_setup_build.py](https://github.com/cupy/cupy/blob/master/cupy_setup_build.py) (`_arch_list`) if needed. -> *no changes needed*
  - [X] Backport. -> *not needed*
- [x] Update bundled FP16 header files.
  - [x] Copy FP16 header files to `cupy/core/include/cupy/_cuda/`, then update `cupy/core/core.pyx` to use it. https://github.com/cupy/cupy/pull/5218
  - [x] Backport. #5232
- [x] Update library installer.
  - [x] Fix `cupyx/tools/install_library.py`. https://github.com/cupy/cupy/pull/5219
  - [x] Backport. #5235
- [x] Wheel distribution -> https://github.com/cupy/cupy-release-tools/pull/111
  - [x] Update cupy-release-tools. https://github.com/cupy/cupy-release-tools/pull/111
  - [x] Ask PyPI team to increase the limit.
- [x] Documentation
  - [x] Add new wheel package to [Installtion Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`. Update requirements in the installation guide. https://github.com/cupy/cupy/pull/5220
  - [x] Backport.
  - [x] Add new wheel package to the [website](https://cupy.dev). https://github.com/cupy/cupy.dev/pull/45
- [x] Implement new features using the version, if any.

Blocked by https://github.com/cupy/cupy/issues/5105

**Comment by leofang** [comment]
I think we hard-wired `CUDA_VERSION` in a few places (say `driver.get_build_version()`). We may need to verify if building on CUDA 11.2 and running on 11.3 is OK (I guess so).

**Comment by kmaehashi** [comment]
If we support APIs added in CUDA 11.3 in CuPy code base, CuPy wheel for CUDA 11.2 will contain a stub signature (null implementation) of such APIs. But that will cause signature conflict (between null implementation and real implementation in CUDA) if the wheel is installed under CUDA 11.3 environment. So... what can we do?

* Release a wheel for each CUDA version as we have been doing
* Do not add support for new API introduced within minor releases (use `ifdef CUDA_VERSION < 12000` instead of `ifdef CUDA_VERSION < 11020` for such API stubs) (I don't want to do this)
* Any ideas?

**Comment by kmaehashi** [comment]
cuDNN for CUDA 11.3 is not available yet: https://developer.nvidia.com/rdp/cudnn-download
cuTENSOR does not care about minor version: `CUDA 11.x` https://developer.nvidia.com/cutensor/downloads
NCCL: https://github.com/cupy/cupy/issues/5105

**Comment by leofang** [comment]
> So... what can we do?

Sorry @kmaehashi for dropping the ball 😅 My own preference would  be to release a wheel for each CUDA as it makes our life simpler. 

But, I just came across the new [device entry point access](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#driver-entry-point-access) added since 11.3. I am still digesting it as I do not understand how to use it properly, but I feel it might provide us a clue to an alternative solution for the 11.x support challenge.

**Comment by leofang** [comment]
FYI: Using driver from 11.2 and runtime from 11.3 is not going to work:
```
$ python -c "import cupy; cupy.show_config()"
OS                           : Linux-5.4.0-42-generic-x86_64-with-glibc2.10
CuPy Version                 : 9.0.0rc1
NumPy Version                : 1.20.2
SciPy Version                : 1.6.3
Cython Build Version         : 0.29.23
Cython Runtime Version       : 0.29.23
CUDA Root                    : /usr/local/cuda-11.3
CUDA Build Version           : 11030
CUDA Driver Version          : 11020
CUDA Runtime Version         : 11030
cuBLAS Version               : 11402
cuFFT Version                : 10402
cuRAND Version               : 10204
cuSOLVER Version             : (11, 1, 1)
cuSPARSE Version             : 11500
NVRTC Version                : (11, 3)
Thrust Version               : 101100
CUB Build Version            : 101100
Jitify Build Version         : 60e9e72
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : 2507
NCCL Runtime Version         : 2507
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : GeForce RTX 2080 Ti
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:1A:00.0
```
Error 1:
```
$ pytest tests/cupy_tests/core_tests/test_raw.py -x
========================================================================= test session starts =========================================================================
platform linux -- Python 3.8.8, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/leofang/dev/cupy_cuda113, configfile: setup.cfg
collected 231 items                                                                                                                                                   

tests/cupy_tests/core_tests/test_raw.py F

============================================================================== FAILURES ===============================================================================
____________________________________________________ TestRaw_param_0_{backend='nvrtc', in_memory=False}.test_basic ____________________________________________________

self = <<cupy_tests.core_tests.test_raw.TestRaw_param_0_{backend='nvrtc', in_memory=False} testMethod=test_basic>  parameter: {'backend': 'nvrtc', 'in_memory': False}>

    def test_basic(self):
>       x1, x2, y = self._helper(self.kern, cupy.float32)

tests/cupy_tests/core_tests/test_raw.py:453: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/cupy_tests/core_tests/test_raw.py:446: in _helper
    x1 = cupy.arange(N**2, dtype=dtype).reshape(N, N)
cupy/_creation/ranges.py:57: in arange
    _arange_ufunc(typ(start), typ(step), ret, dtype=dtype)
cupy/_core/_kernel.pyx:1104: in cupy._core._kernel.ufunc.__call__
    kern = self._get_ufunc_kernel(dev_id, op, arginfos)
cupy/_core/_kernel.pyx:1127: in cupy._core._kernel.ufunc._get_ufunc_kernel
    kern = _get_ufunc_kernel(
cupy/_core/_kernel.pyx:901: in cupy._core._kernel._get_ufunc_kernel
    return _get_simple_elementwise_kernel(
cupy/_core/_kernel.pyx:61: in cupy._core._kernel._get_simple_elementwise_kernel
    module = compile_with_cache(module_code, options)
cupy/_core/core.pyx:1999: in cupy._core.core.compile_with_cache
    return cuda.compile_with_cache(
cupy/cuda/compiler.py:432: in compile_with_cache
    return _compile_with_cache_cuda(
cupy/cuda/compiler.py:553: in _compile_with_cache_cuda
    mod.load(cubin)
cupy/cuda/function.pyx:264: in cupy.cuda.function.Module.load
    cpdef load(self, bytes cubin):
cupy/cuda/function.pyx:266: in cupy.cuda.function.Module.load
    self.ptr = driver.moduleLoadData(cubin)
cupy_backends/cuda/api/driver.pyx:253: in cupy_backends.cuda.api.driver.moduleLoadData
    check_status(status)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   raise CUDADriverError(status)
E   cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_UNSUPPORTED_PTX_VERSION: the provided PTX was compiled with an unsupported toolchain.

cupy_backends/cuda/api/driver.pyx:125: CUDADriverError
======================================================================= short test summary info =======================================================================
FAILED tests/cupy_tests/core_tests/test_raw.py::TestRaw_param_0_{backend='nvrtc', in_memory=False}::test_basic - cupy_backends.cuda.api.driver.CUDADriverError: CUDA...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================== 1 failed in 0.54s ==========================================================================
```
Error 2:
```python
>>> import cupy as cp
>>> a = cp.random.random(10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leofang/dev/cupy_cuda113/cupy/random/_sample.py", line 156, in random_sample
    return rs.random_sample(size=size, dtype=dtype)
  File "/home/leofang/dev/cupy_cuda113/cupy/random/_generator.py", line 618, in random_sample
    out = self._random_sample_raw(size, dtype)
  File "/home/leofang/dev/cupy_cuda113/cupy/random/_generator.py", line 605, in _random_sample_raw
    func(self._generator, out.data.ptr, out.size)
  File "cupy_backends/cuda/libs/curand.pyx", line 163, in cupy_backends.cuda.libs.curand.generateUniformDouble
    cpdef generateUniformDouble(size_t generator, size_t outputPtr, size_t num):
  File "cupy_backends/cuda/libs/curand.pyx", line 167, in cupy_backends.cuda.libs.curand.generateUniformDouble
    check_status(status)
  File "cupy_backends/cuda/libs/curand.pyx", line 86, in cupy_backends.cuda.libs.curand.check_status
    raise CURANDError(status)
cupy_backends.cuda.libs.curand.CURANDError: CURAND_STATUS_LAUNCH_FAILURE
```
