### ISSUE TITLE
Support NCCL 2.9.6

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5105]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuDNN](https://docs.google.com/document/d/1NA1fg-Lqub44dIaArvBdKhrmw4VSYYCmP2cvd8O648k/edit#) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- [ ] Update chainer-test to test version.
- [ ] Update the library installer.
  - [ ] Fix `cupyx/tools/install_library.py`.
  - [ ] Backport.
- [ ] Wheel distribution
  - [ ] Update cupy-release-tools.
- [ ] Documentation
  - [ ] Update Requirements section in [Installtion Guide](https://docs.cupy.dev/en/latest/install.html)
- [ ] Implement new features using the version, if any.

----

https://developer.nvidia.com/nccl/nccl-download
```
Download NCCL 2.9.6, for CUDA 11.3, April 15, 2021
Download NCCL 2.9.6, for CUDA 11.0, April 15, 2021
Download NCCL 2.9.6, for CUDA 10.2, April 15, 2021
```

**Comment by kmaehashi** [comment]
Closing as NCCL 2.9.8 support is now ongoing #5195
