### ISSUE TITLE
Support cuDNN 8.2

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5135]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuDNN](https://docs.google.com/document/d/1NA1fg-Lqub44dIaArvBdKhrmw4VSYYCmP2cvd8O648k/edit#) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- [x] Update chainer-test to test version. https://github.com/chainer/chainer-test/pull/653
- [x] Update the library installer.
  - [x] Fix `cupyx/tools/install_library.py`. https://github.com/cupy/cupy/pull/5146
  - [x] Backport. https://github.com/cupy/cupy/pull/5216
- [x] ~~Wheel distribution~~
  - [x] ~~Update cupy-release-tools.~~
- [x] Documentation
  - [x] Update Requirements section in [Installtion Guide](https://docs.cupy.dev/en/latest/install.html) , https://github.com/cupy/cupy/pull/5148
  - [x] Backport. https://github.com/cupy/cupy/pull/5217
- [x] Implement new features using the version, if any.

**Comment by takagi** [comment]
- [ ]Update chainer-test 
- [ ]Update library installer tool
- [ ]Update wheel distribution
- [ ]Update document

**Comment by takagi** [comment]
Now that `cupy-release-tools` uses the library installer to install cuDNN on Windows, https://github.com/cupy/cupy-release-tools/pull/79, we don't need to update it here.

**Comment by kmaehashi** [comment]
Right! Could you update the wiki?

**Comment by takagi** [comment]
Done!

**Comment by takagi** [comment]
No API changes except for newly supported SWISH activation.
https://docs.nvidia.com/deeplearning/cudnn/api/index.html#release-820

**Comment by kmaehashi** [comment]
Done, thanks @takagi!
