### ISSUE TITLE
Support cuTENSOR 1.3

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5165]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuDNN](https://docs.google.com/document/d/1NA1fg-Lqub44dIaArvBdKhrmw4VSYYCmP2cvd8O648k/edit#) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- [x] Update chainer-test to test version. https://github.com/chainer/chainer-test/pull/655
- [x] Update the library installer.
  - [x] Fix `cupyx/tools/install_library.py`. https://github.com/cupy/cupy/pull/5192
  - [x] Backport. https://github.com/cupy/cupy/pull/5234
- [x] Documentation
  - [x] Update Requirements section in [Installtion Guide](https://docs.cupy.dev/en/latest/install.html) https://github.com/cupy/cupy/pull/5196
  - [x] Backport. https://github.com/cupy/cupy/pull/5238
- [x] Implement new features using the version, if any.

**Comment by leofang** [comment]
According to the release note cuTENSOR 1.3 is binary incompatible with 1.2.x, so I suppose this support cannot be backported to v9?

xref: https://github.com/conda-forge/cutensor-feedstock/issues/11

**Comment by takagi** [comment]
No API addition/removal nor its signature change.

```
$ diff 1.2.2/include/cutensor.h 1.3.0/include/cutensor.h
20,21c20,21
< #define CUTENSOR_MINOR 2 //!< cuTensor minor version.
< #define CUTENSOR_PATCH 2 //!< cuTensor patch version.
---
> #define CUTENSOR_MINOR 3 //!< cuTensor minor version.
> #define CUTENSOR_PATCH 0 //!< cuTensor patch version.
256c256
<  * |    typeA   |    typeB   |    typeC   | typeCompute |
---
>  * |    typeA   |    typeB   |    typeC   | typeScalar |
258a259,261
>  * | CUDA_R_16F | CUDA_R_16F | CUDA_R_16F | CUDA_R_32F  |
>  * | CUDA_R_16BF| CUDA_R_16BF| CUDA_R_16BF| CUDA_R_16BF |
>  * | CUDA_R_16BF| CUDA_R_16BF| CUDA_R_16BF| CUDA_R_32F  |
263d265
<  * | CUDA_R_16F | CUDA_R_16F | CUDA_R_16F | CUDA_R_32F  |
287c289
<  * \param[in] typeScalar Scalar type for the intermediate computation.
---
>  * \param[in] typeScalar Denotes the data type for the scalars alpha, beta, and gamma. Moreover, typeScalar determines the data type that is used throughout the computation.
291a294
>  * \retval CUTENSOR_STATUS_ARCH_MISMATCH if the device is either not ready, or the target architecture is not supported.
510a514
>  * \retval CUTENSOR_STATUS_INSUFFICIENT_WORKSPACE if The provided workspace was insufficient.
531a536
>  * | CUDA_R_16BF| CUDA_R_16BF| CUDA_R_16BF| CUDA_R_32F  |
532a538
>  * | CUDA_R_32F | CUDA_R_32F | CUDA_R_32F | CUDA_R_TF32 |
536a543
>  * | CUDA_C_32F | CUDA_C_32F | CUDA_C_32F | CUDA_C_TF32 |
561a569
>  * \retval CUTENSOR_STATUS_CUDA_ERROR if some unknown CUDA error has occurred.
587c595
<  * It the binary opReduce operator provides extra control over what kind of a reduction
---
>  * The binary opReduce operator provides extra control over what kind of a reduction
595a604
>  * | CUDA_R_16F | CUDA_R_16F | CUDA_R_16F | CUDA_R_16F  |
596a606,607
>  * | CUDA_R_16BF| CUDA_R_16BF| CUDA_R_16BF| CUDA_R_16BF |
>  * | CUDA_R_16BF| CUDA_R_16BF| CUDA_R_16BF| CUDA_R_32F  |
$ diff 1.2.2/include/cutensor/types.h 1.3.0/include/cutensor/types.h
204c204
< typedef struct { int64_t fields[640]; /*!< Data */ } cutensorPlanCacheline_t;
---
> typedef struct { int64_t fields[1408]; /*!< Data */ } cutensorPlanCacheline_t;
209c209
< typedef struct { int64_t fields[8192]; /*!< Data */ } cutensorPlanCache_t;
---
> typedef struct { int64_t fields[12*1024]; /*!< Data */ } cutensorPlanCache_t;
214c214
< typedef struct { int64_t fields[64]; /*!< Data */ } cutensorTensorDescriptor_t;
---
> typedef struct { int64_t fields[72]; /*!< Data */ } cutensorTensorDescriptor_t;
219c219
< typedef struct { int64_t fields[256]; /*!< Data */ } cutensorContractionDescriptor_t;
---
> typedef struct { int64_t fields[288]; /*!< Data */ } cutensorContractionDescriptor_t;
224c224
< typedef struct { int64_t fields[640]; /*!< Data */ } cutensorContractionPlan_t;
---
> typedef struct { int64_t fields[1408]; /*!< Data */ } cutensorContractionPlan_t;
```

**Comment by leofang** [comment]
> conda-forge packages may need to pin a cutensor package version to the one used to build CuPy.

I created an issue to track this: https://github.com/conda-forge/cupy-feedstock/issues/129

**Comment by takagi** [comment]
Now all tasks are done!
