### ISSUE TITLE
Support NCCL 2.9.8

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5195]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuDNN](https://docs.google.com/document/d/1NA1fg-Lqub44dIaArvBdKhrmw4VSYYCmP2cvd8O648k/edit#) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- [x] Update chainer-test to test version. https://github.com/chainer/chainer-test/pull/657
- [x] Update the library installer.
  - [x] Fix `cupyx/tools/install_library.py`. https://github.com/cupy/cupy/pull/5201
  - [x] Backport. #5229
- [x] Documentation
  - [x] Update Requirements section in [Installtion Guide](https://docs.cupy.dev/en/latest/install.html) https://github.com/cupy/cupy/pull/5201
  - [x] Backport. #5229
- [x] ~Implement new features using the version, if any.~

**Comment by takagi** [comment]
The release note says NCCL 2.9.8 supports CUDA 10.1, but I can not find the link for CUDA 10.1 binary.

**Comment by leofang** [comment]
Just FYI. On Conda-Forge we build NCCL from source (since it's available on GitHub) for CUDA 9.2 - 11.2. So far no one came to complain, so I assume it still works as of NCCL 2.9.x 😄

**Comment by takagi** [comment]
The tasks are all done!
