### ISSUE TITLE
Support ROCm 4.2

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5213]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read [ROCm Release Notes](https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html).
- [x] Wheel distribution
  - [x] Update cupy-release-tools. https://github.com/cupy/cupy-release-tools/pull/110
  - [x] Backport. https://github.com/cupy/cupy-release-tools/pull/115
- [x] Documentation
  - [x] Add new wheel package to [Installtion Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`. Update requirements in the installation guide.
  - [x] Backport.
  - [x] Add new wheel package to the [website](https://cupy.dev).
- [x] Implement new features using the version, if any.

**Comment by leofang** [comment]
Might be relevant: https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html#changed-environment-variables-for-hip

**Comment by kmaehashi** [comment]
I haven't run a full CI, but seems we need some work:

```py
>>> x = cupy.arange(100, dtype=cupy.float32).reshape(10, 10)
>>> cupy.fft.fft(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maehashi/.pyenv/versions/local-3.9.2/lib/python3.9/site-packages/cupy/fft/_fft.py", line 677, in fft
    return _fft(a, (n,), (axis,), norm, cupy.cuda.cufft.CUFFT_FORWARD)
  File "/home/maehashi/.pyenv/versions/local-3.9.2/lib/python3.9/site-packages/cupy/fft/_fft.py", line 242, in _fft
    a = _fft_c2c(a, direction, norm, axes, overwrite_x, plan=plan)
  File "/home/maehashi/.pyenv/versions/local-3.9.2/lib/python3.9/site-packages/cupy/fft/_fft.py", line 207, in _fft_c2c
    a = _exec_fft(a, direction, 'C2C', norm, axis, overwrite_x, plan=plan)
  File "/home/maehashi/.pyenv/versions/local-3.9.2/lib/python3.9/site-packages/cupy/fft/_fft.py", line 154, in _exec_fft
    plan = cufft.Plan1d(out_size, fft_type, batch, devices=devices)
  File "cupy/cuda/cufft.pyx", line 300, in cupy.cuda.cufft.Plan1d.__init__
  File "cupy/cuda/cufft.pyx", line 344, in cupy.cuda.cufft.Plan1d._single_gpu_get_plan
  File "cupy/cuda/cufft.pyx", line 169, in cupy.cuda.cufft.check_result
cupy.cuda.cufft.CuFFTError: CUFFT_INVALID_VALUE
```

**Comment by leofang** [comment]
I can take a look later today.

**Comment by kmaehashi** [comment]
FFT issue solved via https://github.com/cupy/cupy/pull/5318. Still seeing some failures :eyes: https://kmaehashi.github.io/cupy-rocm-ci-report/master/output_test.log
