### ISSUE TITLE
Support NCCL 2.9.9

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#5258]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuDNN](https://docs.google.com/document/d/1NA1fg-Lqub44dIaArvBdKhrmw4VSYYCmP2cvd8O648k/edit#) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- [x] Update chainer-test to test version. https://github.com/chainer/chainer-test/pull/661
- [x] Update the library installer.
  - [x] Fix `cupyx/tools/install_library.py`. https://github.com/cupy/cupy/pull/5268
  - [x] Backport. https://github.com/cupy/cupy/pull/5402
- [x] ~Documentation~
  - [x] ~Update Requirements section in [Installtion Guide](https://docs.cupy.dev/en/latest/install.html)~
  - [x] ~Backport.~
- [x] ~Implement new features using the version, if any.~

**Comment by takagi** [comment]
Close as done.

**Comment by kmaehashi** [comment]
Thanks @takagi!
