### ISSUE TITLE
Support cuDNN 8.2.1

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#5323]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuDNN](https://docs.nvidia.com/deeplearning/cudnn/release-notes/index.html) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- [x] Update chainer-test to test version. https://github.com/chainer/chainer-test/pull/672
- [x] Update the library installer.
  - [x] Fix `cupyx/tools/install_library.py`. https://github.com/cupy/cupy/pull/5357
  - [x] Backport. https://github.com/cupy/cupy/pull/5372
- [x] ~Documentation~
  - [x] ~Update Requirements section in [Installtion Guide](https://docs.cupy.dev/en/latest/install.html)~
  - [x] ~Backport.~
- [x] ~Implement new features using the version, if any.~

**Comment by takagi** [comment]
Done.
