### ISSUE TITLE
Support NumPy 1.21

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5382]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes.
- [x] Update chainer-test to test against the version. https://github.com/chainer/chainer-test/pull/676
- [x] For NumPy/SciPy, update requirements in `setup.py`.
  - [x] Update the pinned upper bound version (see #4773) https://github.com/cupy/cupy/pull/5453
  - [x] Backport.
- [x] Update documentation
  - [x] Update Requirements section in [Installtion Guide](https://docs.cupy.dev/en/latest/install.html). The baseline version must be updated in the development branch. https://github.com/cupy/cupy/pull/5454
  - [x] Backport. Do not update the baseline version in backport.
- [x] Update CuPy codebase (if needed) and backport.

**Comment by emcastillo** [comment]
Test failures (Update ongoing)

```
FAILED tests/cupy_tests/math_tests/test_trigonometric.py::TestUnwrap::test_unwrap_1dim - AssertionError: ndarrays of different dtypes are returned.
FAILED tests/cupy_tests/math_tests/test_trigonometric.py::TestUnwrap::test_unwrap_1dim_with_discont - AssertionError: ndarrays of different dtypes are returned.
FAILED tests/cupy_tests/math_tests/test_trigonometric.py::TestUnwrap::test_unwrap_2dim_with_axis - AssertionError: ndarrays of different dtypes are returned.
FAILED tests/cupy_tests/math_tests/test_trigonometric.py::TestUnwrap::test_unwrap_2dim_with_discont - AssertionError: ndarrays of different dtypes are returned.
FAILED tests/cupy_tests/math_tests/test_trigonometric.py::TestUnwrap::test_unwrap_2dim_without_axis - AssertionError: ndarrays of different dtypes are returned.
```
