### ISSUE TITLE
Support CUDA 11.4

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5420]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read [CUDA Release Notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html).
- [x] Update CUDA driver in Linux (Jenkins) / Windows (FlexCI) test infrastructure (ask @kmaehashi).
- [x] ~Update chainer-test to test the CUDA version. https://github.com/chainer/chainer-test/pull/673~ -> Migrated to FlexCI #5457
- [x] Update compute capability support.
  - [x] Check [NVRTC Reference (--gpu-architecture option)](https://docs.nvidia.com/cuda/nvrtc/index.html#group__options) and change the maximum value of supported compute capability defined in [cupy/cuda/compiler.py](https://github.com/cupy/cupy/blob/master/cupy/cuda/compiler.py) (`_nvrtc_max_compute_capability`) if needed. #5434
  - [x] Check [NVCC Reference (--generate-code)](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-steering-gpu-code-generation-generate-code) and change the list of architectures in [cupy_setup_build.py](https://github.com/cupy/cupy/blob/master/cupy_setup_build.py) (`_arch_list`) if needed. #5434
  - [x] Backport. https://github.com/cupy/cupy/pull/5519
- [x] Update bundled FP16 header files.
  - [x] Copy FP16 header files to `cupy/_core/include/cupy/_cuda/`, then update `cupy/_core/core.pyx` to use it. #5434
  - [x] Backport. https://github.com/cupy/cupy/pull/5519
- [x] Update library installer.
  - [x] Fix `cupyx/tools/install_library.py`. #5434
  - [x] Backport. https://github.com/cupy/cupy/pull/5519
- [x] Wheel distribution
  - [x] Update cupy-release-tools. https://github.com/cupy/cupy-release-tools/pull/150
  - [x] Backport.
  - [x] Ask PyPI team to increase the limit. -> not needed any more
- [ ] Documentation
  - [x] Add new wheel package to [Installtion Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`. Update requirements in the installation guide. https://github.com/cupy/cupy/pull/5447
  - [x] Backport. #5535
  - [x] Add new wheel package to the [website](https://cupy.dev). https://github.com/cupy/cupy.dev/pull/46
- [x] Implement new features using the version, if any.

**Comment by kmaehashi** [comment]
CUDA 11.4.1 is out. I checked release notes and I think there's nothing to do in our side. Also confirmed FP16 headers are untouched.
