### ISSUE TITLE
Support cuDNN 8.2.2

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5459]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuSPARSELt](https://docs.nvidia.com/cuda/cusparselt/release_notes.html) / [cuDNN](https://docs.nvidia.com/deeplearning/cudnn/release-notes/index.html) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- [x] Update chainer-test to test version. https://github.com/chainer/chainer-test/pull/678
- [x] Update the library installer.
  - [x] Fix `cupyx/tools/install_library.py`. https://github.com/cupy/cupy/pull/5516
  - [x] Backport. #5523
- [x] ~~Documentation~~
  - [x] ~~Update Requirements section in [Installation Guide](https://docs.cupy.dev/en/latest/install.html)~~
  - [x] ~~Backport.~~
- [x] ~~Implement new features using the version, if any.~~

**Comment by takagi** [comment]
No API chages.
