### ISSUE TITLE
Support NCCL 2.10

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5460]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuSPARSELt](https://docs.nvidia.com/cuda/cusparselt/release_notes.html) / [cuDNN](https://docs.nvidia.com/deeplearning/cudnn/release-notes/index.html) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- [x] Update chainer-test to test version. https://github.com/chainer/chainer-test/pull/680 FlexCI already uses NCCL 2.10: https://github.com/cupy/cupy/blob/019d0b8859c29f7a46f6f6e4b2e9678201492f34/.pfnci/linux/tests/cuda114.Dockerfile#L5
- [x] Update the library installer.
  - [x] Fix `cupyx/tools/install_library.py`. #5521
  - [x] Backport. #5526
- [x] Documentation
  - [x] Update Requirements section in [Installation Guide](https://docs.cupy.dev/en/latest/install.html) #5521 
  - [x] Backport. #5526
- [x] Implement new features using the version, if any. -> raised an issue #5529

**Comment by leofang** [comment]
Looks like there is a new operation [`ncclAvg`](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/types.html?highlight=ncclavg#c.ncclAvg) introduced in NCCL 2.10.

**Comment by takagi** [comment]
I'm going to add `ncclAvg` in another PR.
