### ISSUE TITLE
Support ROCm 4.3

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5592]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [ ] Read [ROCm Release Notes](https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html).
- [ ] Wheel distribution
  - [ ] Update cupy-release-tools.
  - [ ] Backport.
- [ ] Documentation
  - [ ] Add new wheel package to [Installation Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`. Update requirements in the installation guide.
  - [ ] Backport.
  - [ ] Add new wheel package to the [website](https://cupy.dev).
- [ ] Implement new features using the version, if any.

**Comment by leofang** [comment]
`HIP_VERSION` changes from `403` to `40321300`...
https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html#hip-versioning-update

**Comment by kmaehashi** [comment]
We should fix `_cuda_hip_version >= 11010` conditions in `cupy/cuda/compiler.py`

**Comment by takagi** [comment]
> HIP_VERSION changes from 403 to 40321300...

I grepped `HIP_VERSION` and think the change, fortunately, does not affect our code as the newer version will be greater than the version in previous ROCm releases and we do not depend on its format when viewed as a string.

**Comment by takagi** [comment]
I'm also going to check the values we get by `runtimeGetVersion()`.

**Comment by kmaehashi** [comment]
Thanks @takagi! Please check driver versions and build-time versions too. 😄 

Examples (not an exhaustive list):

```
cupy/cuda/memory.pyx:        self.memoryAsyncHasStat = (runtime.driverGetVersion() >= 11030)
```

```
cupyx/scipy/sparse/csr.py:                is_cub_safe &= (driver.get_build_version() < 11000)
```

**Comment by takagi** [comment]
Sure!

**Comment by takagi** [comment]
We're facing the following error when we use hiprtc with ROCm 4.3. 

```
fatal error: '__clang_hip_runtime_wrapper.h' file not found
#include "__clang_hip_runtime_wrapper.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated when compiling for gfx906.
Error: Failed to compile opencl source (from CL or HIP source to LLVM IR).
```

AMD folks say as following:

> It seems this issue is already being worked on. However, it may be sometime before the fix lands on ROCm.
The particular ticket had temporary fix as : Run the program with LLVM_PATH set

**Comment by kmaehashi** [comment]
>  Implement new features using the version, if any.

Let's do this after the release.
