### ISSUE TITLE
Support ROCm 4.3.1

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#5691]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read [ROCm Release Notes](https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html).
- [x] Wheel distribution
  - [x] ~Update cupy-release-tools.~
  - [x] ~Add the package to [duplicate detection](https://github.com/cupy/cupy/blob/master/cupy/_environment.py).~
  - [x] ~Backport.~
- [x] Documentation
  - [x] ~Add new wheel package to [Installation Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`. Update requirements in the installation guide.~
  - [x] ~Backport.~
  - [x] ~Add new wheel package to the [website](https://cupy.dev).~
- [x] ~Implement or create an issue to support new features, if applicable.~

**Comment by kmaehashi** [comment]
I think the only thing to do is https://github.com/cupy/cupy/issues/5689 :smile:

**Comment by takagi** [comment]
This can be closed.
