### ISSUE TITLE
Support NCCL 2.11.4

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#5713]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuSPARSELt](https://docs.nvidia.com/cuda/cusparselt/release_notes.html) / [cuDNN](https://docs.nvidia.com/deeplearning/cudnn/release-notes/index.html) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- [x] Update chainer-test to test version. https://github.com/chainer/chainer-test/pull/686
- [x] Update FlexCI configuration to test the version. 
  - [x] Fix `.pfnci/linux/tests/cuda114.Dockerfile`  #5734
  - [x] Backport. #5747
- [x] Update the library installer.
  - [x] Fix `cupyx/tools/install_library.py`. #5734
  - [x] Backport. #5747
- [x] Documentation
  - [x] Update Requirements section in [Installation Guide](https://docs.cupy.dev/en/latest/install.html) #5734
  - [x] Backport. #5747
- [x] Implement new features using the version, if any.
  - [x] `ncclRedOpCreatePreMulSum` and `ncclRedOpDestroy` #5748

**Comment by takagi** [comment]
Done except for adding new API, for which another PRs raised.
