### ISSUE TITLE
Support cuSPARSELt 0.2.0

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#5812]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuSPARSELt](https://docs.nvidia.com/cuda/cusparselt/release_notes.html) / [cuDNN](https://docs.nvidia.com/deeplearning/cudnn/release-notes/index.html) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- [x] ~Update chainer-test to test the version.~
- Update FlexCI configuration to test the version. 
  - [x] Update `schema.yaml` and `matrix.yaml`, then regenerate stuff. #6436
  - [x] Backport. #6507
- ~Update the library installer.~
  - [x] ~Fix `cupyx/tools/install_library.py`.~
  - [x] ~Backport.~
- Documentation
  - [x] Update Requirements section in [Installation Guide](https://docs.cupy.dev/en/latest/install.html) #6436
  - [x] Backport. #6507
- [x] Implement new features using the version, if any. #6436 #6507

**Comment by takagi** [comment]
Close this to wait next cuSPARSE release #6136.

**Comment by kmaehashi** [comment]
#6430 adds a workaround code in Jitify side so we can work on this again 😄

**Comment by takagi** [comment]
Close as done.
