### ISSUE TITLE
Support Python 3.10

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5837]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes
- [x] Ask fastrlock to release wheels (e.g., https://github.com/scoder/fastrlock/issues/11)
- [x] Update FlexCI variants to use test against new Python version. (note: Some Python libraries may not be supported with the newer versions of Python. In that case you should also limit the library version.) https://github.com/cupy/cupy/pull/5899
- [x] Wheel distribution
  - [x] Update cupy-release-tools. https://github.com/cupy/cupy-release-tools/pull/193
  - [x] Add new Python matrix to the Jenkins job configuration (other_cupy_release_builder).
- [x] Documentation
  - [x] Update Requirements section in [Installation Guide](https://docs.cupy.dev/en/latest/install.html) #6038 
- [x] Update CuPy codebase.
  - [x] Update package Classifier in `setup.py`. #6038
  - [ ] Backport. (no backport this time -- v9 only supports Python ~3.9)

Related task: #4983 (distutils)

**Comment by kmaehashi** [comment]
Let's proceed with this after NumPy / SciPy wheels with the official Py 3.10 support is out. Milestone set to v11 (will be backported to v10.)

**Comment by dvolgyes** [comment]
As far as I see CuPy is not yet supporting python 3.10, and Scipy 1.7.3 is out with python 3.10 support since late November, so shouldn't be this ticket open?

**Comment by kmaehashi** [comment]
@dvolgyes Python 3.10 support has been added in v10.0.0. Let us know if you have any issues.

**Comment by dvolgyes** [comment]
I am sorry, I overlooked that. I will test it out.
