### ISSUE TITLE
Support CUDA 11.5

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#5929]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read [CUDA Release Notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html).
- [x] Update CUDA driver in FlexCI (Linux/Windows) test infrastructure (ask @kmaehashi).
- [x] Add FlexCI configuration for the CUDA version. #5993
- [x] Update compute capability support.
  - [x] Check [NVRTC Reference (--gpu-architecture option)](https://docs.nvidia.com/cuda/nvrtc/index.html#group__options) and change the maximum value of supported compute capability defined in [cupy/cuda/compiler.py](https://github.com/cupy/cupy/blob/master/cupy/cuda/compiler.py) (`_nvrtc_max_compute_capability`) and `_cc_major_map` in `cupy/fft/_callback.pyx`, if needed.
  - [x] Check [NVCC Reference (--generate-code)](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-steering-gpu-code-generation-generate-code) and change the list of architectures in [cupy_setup_build.py](https://github.com/cupy/cupy/blob/master/install/cupy_builder/cupy_setup_build.py) (`arch_list`) if needed.
  - [x] Backport.
- [x] Update bundled FP16 header files.
  - [x] Copy FP16 header files to `cupy/_core/include/cupy/_cuda/`, then update `cupy/_core/core.pyx` to use it.  #5993
  - [x] Backport. #6004
- [x] Update library installer.
  - [x] Fix `cupyx/tools/install_library.py`. #5996
  - [x] Backport. (NOT YET -- blocked by #6005) #6010
- [x] Wheel distribution
  - [x] Update cupy-release-tools. https://github.com/cupy/cupy-release-tools/pull/197
  - [x] Add the package to [duplicate detection](https://github.com/cupy/cupy/blob/master/cupy/_environment.py). #5999
  - [x] Backport.
- [x] Documentation
  - [x] Add new wheel package to [Installation Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`. Update requirements in the installation guide. #5997
  - [x] Backport. #6006
  - [x] Add new wheel package to the [website](https://cupy.dev). https://github.com/cupy/cupy.dev/pull/53
- [x] Implement or create an issue to support new features, if applicable.

**Comment by galipremsagar** [comment]
Hi,

In `cudf`, We seem to be having issues when using latest cupy with cuda 11.5,

```python
cupy/_core/core.pyx:475: in cupy._core.core.ndarray.copy
    ???
cupy/_core/core.pyx:501: in cupy._core.core.ndarray.copy
    ???
cupy/_core/core.pyx:470: in cupy._core.core.ndarray.astype
    ???
cupy/_core/_kernel.pyx:1185: in cupy._core._kernel.ufunc.__call__
    ???
cupy/_core/_kernel.pyx:1212: in cupy._core._kernel.ufunc._get_ufunc_kernel
    ???
cupy/_core/_kernel.pyx:952: in cupy._core._kernel._get_ufunc_kernel
    ???
cupy/_core/_kernel.pyx:62: in cupy._core._kernel._get_simple_elementwise_kernel
    ???
cupy/_core/core.pyx:2042: in cupy._core.core.compile_with_cache
    ???
/opt/conda/envs/rapids/lib/python3.8/site-packages/cupy/cuda/compiler.py:460: in compile_with_cache
    return _compile_with_cache_cuda(
/opt/conda/envs/rapids/lib/python3.8/site-packages/cupy/cuda/compiler.py:538: in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
/opt/conda/envs/rapids/lib/python3.8/site-packages/cupy/cuda/compiler.py:298: in compile_using_nvrtc
    return _compile(source, options, cu_path,
/opt/conda/envs/rapids/lib/python3.8/site-packages/cupy/cuda/compiler.py:282: in _compile
    compiled_obj, mapping = prog.compile(options, log_stream)
/opt/conda/envs/rapids/lib/python3.8/site-packages/cupy/cuda/compiler.py:670: in compile
    raise CompileException(log, self.src, self.name, options,
E   cupy.cuda.compiler.CompileException: /opt/conda/envs/rapids/lib/python3.8/site-packages/cupy/_core/include/cupy/carray.cuh(39): catastrophic error: cannot open source file "cuda_fp16.h"
E   
E   1 catastrophic error detected in the compilation of "/tmp/tmpk8w6vy4s/449cc3731d9f640acab5a909ec4df1d0_2.cubin.cu".
E   Compilation terminated.
```

Does this issues aim at resolving the above error?

**Comment by leofang** [comment]
> Does this issue aim at resolving the above error?

Yes.
