### ISSUE TITLE
Support ROCm 4.5

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#5961]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read [ROCm Release Notes](https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html).
- [ ] Add FlexCI configuration for the ROCm version. #6092
- [ ] Update the image for ROCm build test in `.github/workflows/pretest.yml` #6092
- [ ] Wheel distribution
  - [ ] Update cupy-release-tools.
  - [ ] Add the package to [duplicate detection](https://github.com/cupy/cupy/blob/master/cupy/_environment.py). #6092
  - [ ] Backport.
- [ ] Documentation
  - [ ] Add new wheel package to [Installation Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`. Update requirements in the installation guide. #6092
  - [ ] Backport.
  - [ ] Add new wheel package to the [website](https://cupy.dev).
- [ ] Implement or create an issue to support new features, if applicable.

**Comment by takagi** [comment]
ROCm 4.5.2 is out, and I will check if the half float representation issue is gone.

**Comment by takagi** [comment]
It seems the issue is still alive with ROCm 4.5.2.

```Python
>>> import cupy as cp
>>> cp.show_config()
OS                        : Linux-4.15.0-153-generic-x86_64-with-glibc2.27
Python Version            : 3.9.7
CuPy Version              : 10.0.0rc1
CuPy Platform             : AMD ROCm
NumPy Version             : 1.21.3
SciPy Version             : 1.7.1
Cython Build Version      : 0.29.25
Cython Runtime Version    : None
CUDA Root                 : /opt/rocm-4.5.2
hipcc PATH                : /opt/rocm-4.5.2/bin/hipcc
CUDA Build Version        : 40421432
CUDA Driver Version       : 40421432
CUDA Runtime Version      : 40421432
cuBLAS Version            : (available)
cuFFT Version             : 100
cuRAND Version            : 201009
cuSOLVER Version          : (3, 15, 0)
cuSPARSE Version          : (available)
NVRTC Version             : (9, 0)
Thrust Version            : 101100
CUB Build Version         : 201012
Jitify Build Version      : None
cuDNN Build Version       : None
cuDNN Version             : None
NCCL Build Version        : 2909
NCCL Runtime Version      : 2909
cuTENSOR Version          : None
cuSPARSELt Build Version  : None
Device 0 Name             : Radeon Instinct MI25
Device 0 Arch             : gfx900:xnack-
Device 0 PCI Bus ID       : 0000:1d:00.0
Device 1 Name             : Radeon Vega Frontier Edition
Device 1 Arch             : gfx900:xnack-
Device 1 PCI Bus ID       : 0000:40:00.0
>>> cp.arange(10)
Traceback (most recent call last):
  File "/home/ext-mtakagi/cupy.amd/cupy/cuda/compiler.py", line 680, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 139, in cupy_backends.cuda.libs.nvrtc.compileProgram
    cpdef compileProgram(intptr_t prog, options):
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 151, in cupy_backends.cuda.libs.nvrtc.compileProgram
    check_status(status)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 67, in cupy_backends.cuda.libs.nvrtc.check_status
    raise NVRTCError(status)
cupy_backends.cuda.libs.nvrtc.NVRTCError: HIPRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ext-mtakagi/cupy.amd/cupy/_creation/ranges.py", line 57, in arange
    _arange_ufunc(typ(start), typ(step), ret, dtype=dtype)
  File "cupy/_core/_kernel.pyx", line 1226, in cupy._core._kernel.ufunc.__call__
    kern = self._get_ufunc_kernel(dev_id, op, arginfos, has_where)
  File "cupy/_core/_kernel.pyx", line 1253, in cupy._core._kernel.ufunc._get_ufunc_kernel
    kern = _get_ufunc_kernel(
  File "cupy/_core/_kernel.pyx", line 970, in cupy._core._kernel._get_ufunc_kernel
    return _get_simple_elementwise_kernel(
  File "cupy/_core/_kernel.pyx", line 69, in cupy._core._kernel._get_simple_elementwise_kernel
    module = compile_with_cache(module_code, options)
  File "cupy/_core/core.pyx", line 2122, in cupy._core.core.compile_with_cache
    return cuda.compiler._compile_module_with_cache(
  File "/home/ext-mtakagi/cupy.amd/cupy/cuda/compiler.py", line 483, in _compile_module_with_cache
    return _compile_with_cache_hip(
  File "/home/ext-mtakagi/cupy.amd/cupy/cuda/compiler.py", line 902, in _compile_with_cache_hip
    binary, mapping = compile_using_nvrtc(
  File "/home/ext-mtakagi/cupy.amd/cupy/cuda/compiler.py", line 316, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "/home/ext-mtakagi/cupy.amd/cupy/cuda/compiler.py", line 300, in _compile
    compiled_obj, mapping = prog.compile(options, log_stream)
  File "/home/ext-mtakagi/cupy.amd/cupy/cuda/compiler.py", line 697, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: In file included from /tmp/comgr-25733c/input/CompileSource:2:
/home/ext-mtakagi/cupy.amd/cupy/_core/include/cupy/carray.cuh:94:45: error: no matching conversion for functional-style cast from 'const half' (aka 'const __half') to 'float'
  __device__ operator float() const {return float(data_);}
                                            ^~~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_fp16.h:230:17: note: candidate template ignored: substitution failure [with T = float]: value of type 'std::is_floating_point<float>' is not implicitly convertible to 'bool'
                operator T() const { return data; }
                ^
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_fp16.h:233:13: note: candidate function
            operator __half_raw() const { return __half_raw{data}; }
            ^
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_fp16.h:235:13: note: candidate function
            operator __half_raw() const volatile
            ^
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_fp16.h:244:17: note: candidate template ignored: substitution failure [with T = float]: value of type 'std::is_integral<float>' is not implicitly convertible to 'bool'
                operator T() const { return data; }
                ^
In file included from /tmp/comgr-25733c/input/CompileSource:3:
/home/ext-mtakagi/cupy.amd/cupy/_core/include/cupy/atomics.cuh:32:20: error: no viable conversion from '__half' to 'unsigned short'
    unsigned short sum_as_us = __float2half_rn(__half2float(old_as_us) + float(val));
                   ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_fp16.h:230:17: note: candidate template ignored: substitution failure [with T = unsigned short]: value of type 'std::is_floating_point<unsigned short>' is not implicitly convertible to 'bool'
                operator T() const { return data; }
                ^
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_fp16.h:233:13: note: candidate function
            operator __half_raw() const { return __half_raw{data}; }
            ^
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_fp16.h:235:13: note: candidate function
            operator __half_raw() const volatile
            ^
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_fp16.h:244:17: note: candidate template ignored: substitution failure [with T = unsigned short]: value of type 'std::is_integral<unsigned short>' is not implicitly convertible to 'bool'
                operator T() const { return data; }
                ^
2 errors generated when compiling for gfx900.
Error: Failed to compile source (from CL or HIP source to LLVM IR).
```

**Comment by IvanYashchuk** [comment]
Trying to use ROCm 4.5.0 I also see the compilation error, but it's a bit different:
```py
In [1]: import cupy as cp

In [2]: cp.show_config()
OS                        : Linux-5.4.0-65-generic-x86_64-with-glibc2.10
Python Version            : 3.8.12
CuPy Version              : 10.0.0rc1
CuPy Platform             : AMD ROCm
NumPy Version             : 1.22.1
SciPy Version             : 1.9.0.dev0+1334.0b4785e
Cython Build Version      : 0.29.27
Cython Runtime Version    : 0.29.27
CUDA Root                 : /opt/rocm-4.5.0/
hipcc PATH                : /opt/rocm-4.5.0/bin/hipcc
CUDA Build Version        : 40421401
CUDA Driver Version       : 40421401
CUDA Runtime Version      : 40421401
cuBLAS Version            : (available)
cuFFT Version             : 100
cuRAND Version            : 201009
cuSOLVER Version          : (3, 15, 0)
cuSPARSE Version          : (available)
NVRTC Version             : (9, 0)
Thrust Version            : 101100
CUB Build Version         : 201012
Jitify Build Version      : None
cuDNN Build Version       : None
cuDNN Version             : None
NCCL Build Version        : 2909
NCCL Runtime Version      : 2909
cuTENSOR Version          : None
cuSPARSELt Build Version  : None
Device 0 Name             :
Device 0 Arch             : gfx906:sramecc+:xnack-
Device 0 PCI Bus ID       : 0000:43:00.0
Device 1 Name             :
Device 1 Arch             : gfx906:sramecc+:xnack-
Device 1 PCI Bus ID       : 0000:23:00.0
Device 2 Name             :
Device 2 Arch             : gfx906:sramecc+:xnack-
Device 2 PCI Bus ID       : 0000:26:00.0
Device 3 Name             :
Device 3 Arch             : gfx906:sramecc+:xnack-
Device 3 PCI Bus ID       : 0000:03:00.0
Device 4 Name             :
Device 4 Arch             : gfx906:sramecc+:xnack-
Device 4 PCI Bus ID       : 0000:e3:00.0
Device 5 Name             :
Device 5 Arch             : gfx906:sramecc+:xnack-
Device 5 PCI Bus ID       : 0000:c3:00.0
Device 6 Name             :
Device 6 Arch             : gfx906:sramecc+:xnack-
Device 6 PCI Bus ID       : 0000:c6:00.0
Device 7 Name             :
Device 7 Arch             : gfx906:sramecc+:xnack-
Device 7 PCI Bus ID       : 0000:83:00.0

In [3]: cp.arange(10)
---------------------------------------------------------------------------
NVRTCError                                Traceback (most recent call last)
File ~/miniconda3/envs/scipy-meson/lib/python3.8/site-packages/cupy-10.0.0rc1-py3.8-linux-x86_64.egg/cupy/cuda/compiler.py:681, in _NVRTCProgram.compile(self, options, log_stream)
    680         nvrtc.addNameExpression(self.ptr, ker)
--> 681 nvrtc.compileProgram(self.ptr, options)
    682 mapping = None

File cupy_backends/cuda/libs/nvrtc.pyx:139, in cupy_backends.cuda.libs.nvrtc.compileProgram()

File cupy_backends/cuda/libs/nvrtc.pyx:151, in cupy_backends.cuda.libs.nvrtc.compileProgram()

File cupy_backends/cuda/libs/nvrtc.pyx:67, in cupy_backends.cuda.libs.nvrtc.check_status()

NVRTCError: HIPRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

CompileException                          Traceback (most recent call last)
Input In [3], in <module>
----> 1 cp.arange(10)

File ~/miniconda3/envs/scipy-meson/lib/python3.8/site-packages/cupy-10.0.0rc1-py3.8-linux-x86_64.egg/cupy/_creation/ranges.py:57, in arange(start, stop, step, dtype)
     55 ret = cupy.empty((size,), dtype=dtype)
     56 typ = numpy.dtype(dtype).type
---> 57 _arange_ufunc(typ(start), typ(step), ret, dtype=dtype)
     58 return ret

File cupy/_core/_kernel.pyx:1229, in cupy._core._kernel.ufunc.__call__()

File cupy/_core/_kernel.pyx:1256, in cupy._core._kernel.ufunc._get_ufunc_kernel()

File cupy/_core/_kernel.pyx:973, in cupy._core._kernel._get_ufunc_kernel()

File cupy/_core/_kernel.pyx:71, in cupy._core._kernel._get_simple_elementwise_kernel()

File cupy/_core/core.pyx:2130, in cupy._core.core.compile_with_cache()

File ~/miniconda3/envs/scipy-meson/lib/python3.8/site-packages/cupy-10.0.0rc1-py3.8-linux-x86_64.egg/cupy/cuda/compiler.py:484, in _compile_module_with_cache(source, options, arch, cache_dir, extra_source, backend, enable_cooperative_groups, name_expressions, log_stream, jitify)
    482 if runtime.is_hip:
    483     backend = 'hiprtc' if backend == 'nvrtc' else 'hipcc'
--> 484     return _compile_with_cache_hip(
    485         source, options, arch, cache_dir, extra_source, backend,
    486         name_expressions, log_stream, cache_in_memory)
    487 else:
    488     return _compile_with_cache_cuda(
    489         source, options, arch, cache_dir, extra_source, backend,
    490         enable_cooperative_groups, name_expressions, log_stream,
    491         cache_in_memory, jitify)

File ~/miniconda3/envs/scipy-meson/lib/python3.8/site-packages/cupy-10.0.0rc1-py3.8-linux-x86_64.egg/cupy/cuda/compiler.py:853, in _compile_with_cache_hip(source, options, arch, cache_dir, extra_source, backend, name_expressions, log_stream, cache_in_memory, use_converter)
    850 if base is None:
    851     # This is for checking HIPRTC/HIPCC compiler internal version
    852     if backend == 'hiprtc':
--> 853         base = _preprocess_hiprtc('', options)
    854     else:
    855         base = _preprocess_hipcc('', options)

File ~/miniconda3/envs/scipy-meson/lib/python3.8/site-packages/cupy-10.0.0rc1-py3.8-linux-x86_64.egg/cupy/cuda/compiler.py:770, in _preprocess_hiprtc(source, options)
    763 prog = _NVRTCProgram(
    764     '''
    765     // hiprtc segfaults if the input code is empty
    766     #include <hip/hip_runtime.h>
    767     __global__ void _cupy_preprocess_dummy_kernel_() { }
    768     ''')
    769 try:
--> 770     result, _ = prog.compile(options)
    771 except CompileException as e:
    772     dump = _get_bool_env_variable(
    773         'CUPY_DUMP_CUDA_SOURCE_ON_ERROR', False)

File ~/miniconda3/envs/scipy-meson/lib/python3.8/site-packages/cupy-10.0.0rc1-py3.8-linux-x86_64.egg/cupy/cuda/compiler.py:698, in _NVRTCProgram.compile(self, options, log_stream)
    696 except nvrtc.NVRTCError:
    697     log = nvrtc.getProgramLog(self.ptr)
--> 698     raise CompileException(log, self.src, self.name, options,
    699                            'nvrtc' if not runtime.is_hip else 'hiprtc')

CompileException: In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:55:46: error: redefinition of 'enable_if'
template <bool __B, class __T = void> struct enable_if {};
                                             ^
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:55:46: note: previous definition is here
template <bool __B, class __T = void> struct enable_if {};
                                             ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:56:29: error: redefinition of 'enable_if<true, __T>'
template <class __T> struct enable_if<true, __T> { typedef __T type; };
                            ^~~~~~~~~~~~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:56:29: note: previous definition is here
template <class __T> struct enable_if<true, __T> { typedef __T type; };
                            ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:58:8: error: redefinition of 'true_type'
struct true_type { static const __constant__ bool value = true; };
       ^
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:58:8: note: previous definition is here
struct true_type { static const __attribute__((constant)) bool value = true; };
       ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:59:8: error: redefinition of 'false_type'
struct false_type { static const __constant__ bool value = false; };
       ^
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:59:8: note: previous definition is here
struct false_type { static const __attribute__((constant)) bool value = false; };
       ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:60:26: error: redefinition of 'true_or_false_type'
template<bool _B> struct true_or_false_type : public false_type {};
                         ^
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:60:26: note: previous definition is here
template<bool _B> struct true_or_false_type : public false_type {};
                         ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:61:19: error: redefinition of 'true_or_false_type<true>'
template<> struct true_or_false_type<true> : public true_type {};
                  ^~~~~~~~~~~~~~~~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:61:19: note: previous definition is here
template<> struct true_or_false_type<true> : public true_type {};
                  ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:63:29: error: redefinition of 'is_integral'
template <class _Tp> struct is_integral : public false_type {};
                            ^
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:63:29: note: previous definition is here
template <class _Tp> struct is_integral : public false_type {};
                            ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:64:20: error: redefinition of 'is_integral<bool>'
template <> struct is_integral<bool> : public true_type {};
                   ^~~~~~~~~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:64:20: note: previous definition is here
template <> struct is_integral<bool> : public true_type {};
                   ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:65:20: error: redefinition of 'is_integral<char>'
template <> struct is_integral<char> : public true_type {};
                   ^~~~~~~~~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:65:20: note: previous definition is here
template <> struct is_integral<char> : public true_type {};
                   ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:66:20: error: redefinition of 'is_integral<signed char>'
template <> struct is_integral<signed char> : public true_type {};
                   ^~~~~~~~~~~~~~~~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:66:20: note: previous definition is here
template <> struct is_integral<signed char> : public true_type {};
                   ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:67:20: error: redefinition of 'is_integral<unsigned char>'
template <> struct is_integral<unsigned char> : public true_type {};
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:67:20: note: previous definition is here
template <> struct is_integral<unsigned char> : public true_type {};
                   ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:68:20: error: redefinition of 'is_integral<wchar_t>'
template <> struct is_integral<wchar_t> : public true_type {};
                   ^~~~~~~~~~~~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:68:20: note: previous definition is here
template <> struct is_integral<wchar_t> : public true_type {};
                   ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:69:20: error: redefinition of 'is_integral<short>'
template <> struct is_integral<short> : public true_type {};
                   ^~~~~~~~~~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:69:20: note: previous definition is here
template <> struct is_integral<short> : public true_type {};
                   ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:70:20: error: redefinition of 'is_integral<unsigned short>'
template <> struct is_integral<unsigned short> : public true_type {};
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:70:20: note: previous definition is here
template <> struct is_integral<unsigned short> : public true_type {};
                   ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:71:20: error: redefinition of 'is_integral<int>'
template <> struct is_integral<int> : public true_type {};
                   ^~~~~~~~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:71:20: note: previous definition is here
template <> struct is_integral<int> : public true_type {};
                   ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:72:20: error: redefinition of 'is_integral<unsigned int>'
template <> struct is_integral<unsigned int> : public true_type {};
                   ^~~~~~~~~~~~~~~~~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:72:20: note: previous definition is here
template <> struct is_integral<unsigned int> : public true_type {};
                   ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:73:20: error: redefinition of 'is_integral<long>'
template <> struct is_integral<long> : public true_type {};
                   ^~~~~~~~~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:73:20: note: previous definition is here
template <> struct is_integral<long> : public true_type {};
                   ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:74:20: error: redefinition of 'is_integral<unsigned long>'
template <> struct is_integral<unsigned long> : public true_type {};
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:74:20: note: previous definition is here
template <> struct is_integral<unsigned long> : public true_type {};
                   ^
In file included from /tmp/comgr-c95eba/input/CompileSource:3:
In file included from /opt/rocm-4.5.0/include/hip/hip_runtime.h:62:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_runtime.h:79:
In file included from /opt/rocm-4.5.0/include/hip/amd_detail/hip_ldg.h:27:
/opt/rocm-4.5.0/include/hip/amd_detail/amd_hip_vector_types.h:75:20: error: redefinition of 'is_integral<long long>'
template <> struct is_integral<long long> : public true_type {};
                   ^~~~~~~~~~~~~~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/external/hipamd/include/hip/amd_detail/amd_hip_vector_types.h:75:20: note: previous definition is here
template <> struct is_integral<long long> : public true_type {};
                   ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated when compiling for gfx906.
Error: Failed to compile source (from CL or HIP source to LLVM IR).
```

**Comment by takagi** [comment]
We shared this issue with AMD, and they recognize it. We're waiting for ROCm's update.

**Comment by kmaehashi** [comment]
I think we have to skip supporting ROCm 4.5 as ROCm 5.0 is out (#6459) and ROCm 4.5.x series will unlikely get updated?

**Comment by takagi** [comment]
I agree.
