### ISSUE TITLE
[Tracker] Implement all `numpy.*` APIs in CuPy

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#6078]
Implement GPU version of `numpy.*` functions in `cupy.*` namespace.

This is a tracker issue that lists the remaining `numpy.*` APIs (see also: [comparison table](https://docs.cupy.dev/en/latest/reference/comparison.html#module-level)). I've categorized them based on difficulty (comments welcomed :smile:) so that new contributors can pick the right task. Your contribution is highly welcomed and appreciated!

### Very Easy

- [ ] `numpy.asfarray`
- [ ] `numpy.byte_bounds`
- [ ] `numpy.format_float_positional` (just call NumPy function like `cupy.array2string`)
- [ ] `numpy.format_float_scientific` (just call NumPy function like `cupy.array2string`)
- [ ] `numpy.loads`
- [ ] `numpy.ndfromtxt`

### Easy

- [ ] `numpy.array_equiv`
- [ ] `numpy.asarray_chkfinite` (note: likely to require synchronization)
- [ ] `numpy.fabs`
- [ ] `numpy.float_power`
- [ ] `numpy.heaviside`
- [ ] `numpy.isneginf`
- [ ] `numpy.isposinf`
- [ ] `numpy.ndenumerate`
- [ ] `numpy.real_if_close` (note: likely to require synchronization)
- [ ] `numpy.tril_indices_from` (just wrap NumPy function)

These are also considered easy tasks but relatively low priority:

- [ ] `numpy.deprecate`
- [ ] `numpy.deprecate_with_doc`
- [ ] `numpy.info`
- [ ] `numpy.lookfor`
- [ ] `numpy.source`

### Medium

- [ ] `numpy.apply_over_axes`
- [ ] `numpy.block`
- [ ] `numpy.cast` (note: undocumented API in `numpy/core/numerictypes.py`)
- [ ] `numpy.delete`
- [ ] `numpy.einsum_path`
- [ ] `numpy.frompyfunc` (maybe just call GUFunc?)
- [ ] `numpy.geomspace`
- [ ] `numpy.insert`
- [ ] `numpy.nested_iters`
- [ ] `numpy.nditer`
- [ ] `numpy.put_along_axis`
- [ ] `numpy.row_stack`
- [ ] `numpy.set_numeric_ops`
- [ ] `numpy.spacing`
- [ ] `numpy.vander`

### Medium to High

- [ ] `numpy.histogram_bin_edges`
- [ ] `numpy.setxor1d`
- [ ] `numpy.ediff1d`
- [ ] `numpy.intersect1d`
- [ ] `numpy.nanpercentile`
- [ ] `numpy.nanquantile`
- [ ] `numpy.poly` (#3547)
- [ ] `numpy.polyder`
- [ ] `numpy.polydiv` (#3780)
- [ ] `numpy.polyint`
- [ ] `numpy.setdiff1d`
- [ ] `numpy.trapz`
- [ ] `numpy.union1d`

## Steps to Contribute

1. Fork and star :star: the CuPy repository :wink:

1. Pick a function you want to work on. You can find the function in the [NumPy API Reference](https://numpy.org/doc/stable/reference/routines.html) to understand what should be implemented.

1. Implement a function in your branch. If you need help, join [Gitter](https://gitter.im/cupy/community) or just ask for help in this issue.

1. Don't forget to write a test code!

1. Build CuPy and run tests to confirm that the function runs fine:
  `pip install -e . && pytest tests/cupy_tests/PATH_TO_YOUR_TEST`
   See the [Contribution Guide](https://docs.cupy.dev/en/latest/contribution.html#unit-testing) for details.

1. Submit a pull-request to the `master` branch.

Note that you will need a GPU environment to develop CuPy.

**Comment by khushi-411** [comment]
Hi @kmaehashi,
I am glad to look into the awesome collection of required APIs. 

I was wondering if other APIs for constant functions like `numpy.inf`, `numpy.ninf` etc can also be added to the `cupy` library. Curious to know your viewpoints. Thanks!

**NumPy Reference**: https://numpy.org/devdocs/reference/constants.html.

**Comment by kmaehashi** [comment]
@khushi-411 Thanks for pull-requests! All constants are imported in CuPy 😄 
 https://github.com/cupy/cupy/blob/v10.0.0rc1/cupy/__init__.py#L56-L73

**Comment by jakirkham** [comment]
cc @leofang @grlee77 @rgommers

**Comment by rgommers** [comment]
There's a whole bunch of very questionable stuff here, including things that are deprecated. It does not make sense to me to add those. But rather than spend time arguing about that, let me just go work on a PR to remove them from NumPy:)

**Comment by jakirkham** [comment]
Yeah some of the easy and very easy things read that way to me

The medium & medium to hard seem ok though (with the exception of the typing stuff)

The iterating functions (particularly on GPUs) I'm not sure about, but maybe Leo has thoughts there.

Anything else stick out to you, Ralf? Does the above sound roughly correct to you or are there other things that stick out?

**Comment by leofang** [comment]
@rgommers Could you list what is deprecated/inappropriate? I thought @kmaehashi has avoided listing them.

**Comment by rgommers** [comment]
`loads` and `ndfromtxt` were already removed in https://github.com/numpy/numpy/pull/19615, so can be removed from the list.

> The medium & medium to hard seem ok though (with the exception of the typing stuff)

With "typing stuff" do you mean the dtype-related functions (`cast`, `typecodes`, etc.)? If so, then I agree - that's questionable. Also xref https://github.com/numpy/numpy/issues/17325 for that.

> The iterating functions (particularly on GPUs) I'm not sure about, but maybe Leo has thoughts there.
>
> Anything else stick out to you, Ralf? Does the above sound roughly correct to you or are there other things that stick out?

That sounds about right. The `random` and `linalg` stuff is important, as are some of the medium-hard functions like `put_along_axis`, `nanquantile`, `nanpercentile`, etc.

All of the undocumented ones I'd like to get rid of in NumPy.

**Comment by jakirkham** [comment]
> > The medium & medium to hard seem ok though (with the exception of the typing stuff)
> 
> With "typing stuff" do you mean the dtype-related functions (`cast`, `typecodes`, etc.)? If so, then I agree - that's questionable. Also xref [numpy/numpy#17325](https://github.com/numpy/numpy/issues/17325) for that.

Yeah exactly. Sorry that was vague

**Comment by rgommers** [comment]
`alen` and `asscalar` will be removed in 1.23.0 (probably, unless it still gets backported to `1.22.x`) by https://github.com/numpy/numpy/pull/20414

**Comment by rgommers** [comment]
See also:

https://github.com/numpy/numpy/blob/main/numpy/tests/test_public_api.py#L33-L54

**Comment by kmaehashi** [comment]
@rgommers Thank you for all the information. I've removed deprecated ones from the list:

- `numpy.loads`
- `numpy.ndfromtxt`
- `numpy.alen`
- `numpy.asscalar`
- `numpy.ndarray.tostring`
- `numpy.set_numeric_ops`

Also marked dtype-related functions as low priority as there's an ongoing discussion in NumPy.

**Comment by knshkp** [comment]
i also want to contribute in this library but when i seen this all issues are resolved so could you please assign me a tasks

**Comment by pri1311** [comment]
Hey! I was working on `numpy.setxor1d` but seems like when you provide a 2D array with assume_unique as True, numpy raises an error, since their code concatenates array as - `np.concatenate((ar1,ar2))` and not `np.concatenate((ar1,ar2), axis=None)`.
However, when assume_unique is false, the array is flattened as it uses the `numpy.unique` function which returns a flattened array. Do we replicate the same behaviour in CuPy or allow 2D arrays even when assume_unique is set to true?

Attaching a screenshot below to explain the above:
 
<img width="670" alt="image" src="https://user-images.githubusercontent.com/64613009/159218884-0c0ac806-b821-477b-b68a-bec7ef48077e.png">

**Comment by Nordicus** [comment]
I've noticed that the automatic domain functions (numpy.emath.* or numpy.lib.scimath.*) seem to be missing from this. Is this a mistake, or are they not supposed to be supported?
https://numpy.org/doc/stable/reference/routines.emath.html

**Comment by kmaehashi** [comment]
@Nordicus Yes it's just because I overlooked it, thanks for the catch! 😄

**Comment by pri1311** [comment]
Hi team, I was looking into implementing `cupy.emath.*` and I believe the implementation is pretty simple. And since all our functions `sqrt`, `log`, etc are implemented using ufunc and already support complex numbers it is just a matter of converting any negatives into complex numbers like in numpy with no other changes required. Is my thinking correct? Pardon my negligence if any.

**Comment by kmaehashi** [comment]
@pri1311 Hi, I agree it should be that simple.

**Comment by yonikremer** [comment]
@kmaehashi please chek `numpy.lib.stride_tricks.sliding_window_view`. It was implemented and merged in [Add `cupy.lib.stride_tricks.sliding_window_view`](https://github.com/cupy/cupy/pull/7575)

**Comment by yonikremer** [comment]
`numpy.ndarray.itemset` was removed in numpy 2.0, So please remove it from the list.

**Comment by kmaehashi** [comment]
@kgryte I suppose you are browsing v13 docs. `put_along_axis` is listed here:
https://docs.cupy.dev/en/latest/reference/indexing.html#inserting-data-into-arrays

**Comment by kmaehashi** [comment]
Added following APIs to the table.

- `numpy.bitwise_count`
- `numpy.cumulative_prod`
- `numpy.cumulative_sum`
- `numpy.matrix_transpose`
- `numpy.unstack`
- `numpy.vecdot`
- `numpy.linalg.diagonal`
- `numpy.linalg.matmul`
- `numpy.linalg.matrix_norm`
- `numpy.linalg.matrix_transpose`
- `numpy.linalg.outer`
- `numpy.linalg.svdvals`
- `numpy.linalg.tensordot`
- `numpy.linalg.trace`
- `numpy.linalg.vecdot`
- `numpy.linalg.vector_norm`

**Comment by vin-prabhakar** [comment]
Hello @kmaehashi 

I want to work on implementing numpy.cumulative_sum. Is there a way to get assigned, or should I raise the PR directly ?

Thanks !

**Comment by kmaehashi** [comment]
Hi @vprabhakar12, feel free to open a PR directly.

**Comment by pugalvini** [comment]
Hi! I'd like to work on cupy.bitwise_count as my first contribution. Let me know if it's okay to proceed. Thanks!

**Comment by kiranlahiri** [comment]
Hello! I would like to work on numpy.cumulative_sum in CuPy as I'm looking to make my first contribution. Is this alright? Thank you!

EDIT: I see somebody else already requested numpy.cumulative_sum. Can I do numpy.cumulative_prod instead?

**Comment by vin-prabhakar** [comment]
@kiranlahiri , I've written the cupy.cumulative_sum so that both cumulative_sum and cumulative_prod uses a common function, similar to numpy. 
The cumulative_sum function is working . I'm waiting for some confirmation on how to implement the test cases.
Once this this time I guess cumulative_prod wouldn't a lot of work. 
@kmaehashi could you check my draft for cumulative_sum?

**Comment by kiranlahiri** [comment]
@vprabhakar12 Sounds good I can pick something else. Can I take numpy.matrix_transpose then?

**Comment by 0xtoward** [comment]
Hi, I’m a first-year PhD student in HPC and new to contributing here.  
I’d like to start with some of the (Very) Easy items.  
Could I take on numpy.bitwise_count svdvals ect..?

**Comment by coolenough** [comment]
Hello @kmaehashi

I want to work on implementing numpy.linalg.trace. Is there a way to get assigned, or should I raise the PR directly ?

Thanks !

**Comment by DanielCohenn** [comment]
Hey all !
Wanted to notify you that I am starting to work on the `numpy.cumulative_prod` function. @kmaehashi

**Comment by Bhuvan1527** [comment]
Hi everyone

Wanted inform that I've raised the pr for adding support for cupy.isdtype . 
@kmaehashi -san requesting review.
Pr for reference: https://github.com/cupy/cupy/pull/9884

**Comment by Bhuvan1527** [comment]
Hi everyone. 

Please find the pr for cupy.linalg.matmul and cupy.linalg.matrix_transpose

Pr: https://github.com/cupy/cupy/pull/9892

**Comment by ray-singh** [comment]
Hi @kmaehashi , I'd like to contribute to adding numpy.linalg.diagonal, numpy.matrix_transpose, and numpy.vecdot if they're still unassigned. Is there a way to get assigned, or should I open a PR directly? Thank you!

**Comment by Bhuvan1527** [comment]
> Hi [@kmaehashi](https://github.com/kmaehashi) , I'd like to contribute to adding numpy.linalg.diagonal, numpy.matrix_transpose, and numpy.vecdot if they're still unassigned. Is there a way to get assigned, or should I open a PR directly? Thank you!

Hi @ray-singh . I have already handled numpy.linalg.diagonal in the pr https://github.com/cupy/cupy/pull/9952 . Requesting you to pick a different one. 

Thanks

**Comment by ray-singh** [comment]
Thanks for letting me know @Bhuvan1527 ; I'll work on numpy.matrix_transpose, numpy.vecdot, and numpy.block instead. Do I need to be assigned or can I start working on them?

**Comment by tanishqtayade** [comment]
Hi @kmaehashi, I had like to work on numpy.linalg.vector_norm. Is this still available? I'll open a PR once I confirm it's unassigned.

**Comment by shxunxk** [comment]
I would like to work on this. May I know if this is still open or already resolved? I waould like to work on 

numpy.block
numpy.unstack
numpy.spacing

could i have it assigned to me

**Comment by seberg** [comment]
As a general note, please don't ask to be assigned to this issue, simply open a PR about something specific and link back.  When in doubt about niche API then let us know (in the above, `spacing` seems a bit niche, but fine.).
