### ISSUE TITLE
Support CUDA 11.5.1

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#6154]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read [CUDA Release Notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html).
- [x] Update CUDA driver in FlexCI (Linux/Windows) test infrastructure (ask @kmaehashi). -> not needed
- [x] ~Add FlexCI configuration for the CUDA version.~
- [ ] Update compute capability support.
  - [x] Check [NVRTC Reference (--gpu-architecture option)](https://docs.nvidia.com/cuda/nvrtc/index.html#group__options) and change the maximum value of supported compute capability defined in [cupy/cuda/compiler.py](https://github.com/cupy/cupy/blob/master/cupy/cuda/compiler.py) (`_nvrtc_max_compute_capability`) and `_cc_major_map` in `cupy/fft/_callback.pyx`, if needed. #6166
  - [x] Check [NVCC Reference (--generate-code)](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-steering-gpu-code-generation-generate-code) and change the list of architectures in [cupy_setup_build.py](https://github.com/cupy/cupy/blob/master/install/cupy_builder/cupy_setup_build.py) (`_arch_list`) if needed. #6166
  - [x] Backport. #6331
- [x] ~Update bundled FP16 header files.~
  - [x] ~Copy FP16 header files to `cupy/_core/include/cupy/_cuda/`, then update `cupy/_core/core.pyx` to use it.~
  - [x] ~Backport.~
- [x] ~Update library installer.~
  - [x] ~Fix `cupyx/tools/install_library.py`.~
  - [x] ~Backport.~
- [x] ~Wheel distribution~
  - [x] ~Update cupy-release-tools. https://github.com/cupy/cupy-release-tools/pull/221~
  - [x] ~Add the package to [duplicate detection](https://github.com/cupy/cupy/blob/master/cupy/_environment.py).~
  - [x] ~Backport.~
- [x] ~Documentation~
  - [x] ~Add new wheel package to [Installation Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`. Update requirements in the installation guide.~
  - [x] ~Backport.~
  - [x] ~Add new wheel package to the [website](https://cupy.dev).~
- [x] ~Implement or create an issue to support new features, if applicable.~

**Comment by kmaehashi** [comment]
I guess NVRTC also supports compute_87?

**Comment by takagi** [comment]
Ah, the document doesn't say so, but I want to check what nvrtc says.

**Comment by leofang** [comment]
Yes, please check with `nvrtcGetSupportedArchs()`. NVRTC docs are not fully up-to-date and I've brought it to internal attention a while ago. For example, `sm_86`/`compute_86` are also missing (but they've been supported since early 11.x).

**Comment by takagi** [comment]
```Python
>>> nvrtc.getSupportedArchs()
(35, 37, 50, 52, 53, 60, 61, 62, 70, 72, 75, 80, 86, 87)
```

**Comment by takagi** [comment]
I also checked '87' is supported since CUDA 11.4 for both nvcc and nvrtc.

**Comment by kmaehashi** [comment]
Done, thanks @takagi!
