### ISSUE TITLE
Support cuTENSOR 1.4.0

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#6177]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuSPARSELt](https://docs.nvidia.com/cuda/cusparselt/release_notes.html) / [cuDNN](https://docs.nvidia.com/deeplearning/cudnn/release-notes/index.html) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- [x] Update FlexCI configuration to test the version. 
  - [x] Fix `.pfnci/schema.yaml` and `.pfnci/matirx.yaml` #6187
  - [x] Backport. #6330
- [x] Update the library installer.
  - [x] Fix `cupyx/tools/install_library.py`. #6187
  - [x] Backport. #6330
- [x] Documentation
  - [x] Update Requirements section in [Installation Guide](https://docs.cupy.dev/en/latest/install.html) #6187
  - [x] Backport. #6330
- [x] Implement new features using the version, if any. #6187

**Comment by takagi** [comment]
cuTENSOR 1.4 has preview support for distributed, multi-GPU tensor operations, whose API is prefixed as `cutensorMgXxx`.

**Comment by leofang** [comment]
btw although the release note didn't say it explicitly, 1.4.0 is again binary incompatible with earlier versions, not sure if this has any impact to CuPy's support, though

**Comment by leofang** [comment]
Sorry, ignore my comment above, that was my misunderstanding.

**Comment by takagi** [comment]
The only effective change in the header files is adding `CUTENSOR_ALGO_DEFAULT_PATIENT` to `cutensorAlgo_t`.

**Comment by takagi** [comment]
Close as done.
