### ISSUE TITLE
Support SciPy 1.8

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#6233]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes.
- [x] Update FlexCI schema/matrix to test against the version. #6365
- [x] For NumPy/SciPy, update requirements in `setup.py`.
  - [x] Update the pinned upper bound version (see #4773) #6365
  - [x] Backport. #6444
- [x] Update documentation
  - [x] Update Requirements section in [Installation Guide](https://docs.cupy.dev/en/latest/install.html). The baseline version must be updated in the development branch. #6365
  - [x] Update `docs/requirements.txt` to use the latest versions. #6365
  - [x] Backport. Do not update the baseline version in backport. #6444
- [x] Update CuPy codebase (if needed) and backport.
  - #6249
  - #6253
  - #6252

**Comment by kmaehashi** [comment]
Test failures with SciPy 1.8 RC: https://ci.preferred.jp/cupy.linux.cuda-head/88919/

It seems issues fail into 3 categories:

* ValueError: Scalar operands are not allowed, use '*' instead
    * using `@` against scalar?
* DeprecationWarning: Please use `spmatrix` from the `scipy.sparse` namespace, the `scipy.sparse.base` namespace is deprecated.
* AssertionError: ndarrays of different dtypes are returned.

**Comment by takagi** [comment]
> This package is switching to an array interface, compatible with NumPy arrays, from the older matrix interface. We recommend that you use the array objects (bsr_array, coo_array, etc.) for all new work.

https://scipy.github.io/devdocs/reference/sparse.html#sparse-matrices-scipy-sparse

**Comment by takagi** [comment]
Done.
