### ISSUE TITLE
Support CUDA 11.6

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#6309]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read [CUDA Release Notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html).
- [x] Update CUDA driver in FlexCI (Linux/Windows) test infrastructure (ask @kmaehashi).
- [x] Add FlexCI configuration for the CUDA version. #6349
- [x] ~Update compute capability support.~
  - [x] ~Check [NVRTC Reference (--gpu-architecture option)](https://docs.nvidia.com/cuda/nvrtc/index.html#group__options) and change the maximum value of supported compute capability defined in [cupy/cuda/compiler.py](https://github.com/cupy/cupy/blob/master/cupy/cuda/compiler.py) (`_nvrtc_max_compute_capability`) and `_cc_major_map` in `cupy/fft/_callback.pyx`, if needed.~
  - [x] ~Check [NVCC Reference (--generate-code)](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-steering-gpu-code-generation-generate-code) and change the list of architectures in [cupy_setup_build.py](https://github.com/cupy/cupy/blob/master/install/cupy_builder/cupy_setup_build.py) (`_arch_list`) if needed.~
  - [x] ~Backport.~
- [x] Update bundled FP16 header files.
  - [x] Copy FP16 header files to `cupy/_core/include/cupy/_cuda/`, then update `cupy/_core/core.pyx` to use it. #6349
  - [x] Backport. #6422
- [x] Update library installer.
  - [x] Fix `cupyx/tools/install_library.py`. #6349
  - [x] Backport. #6422
- [x] Wheel distribution
  - [x] Update cupy-release-tools. https://github.com/cupy/cupy-release-tools/pull/236
  - [x] Add the package to [duplicate detection](https://github.com/cupy/cupy/blob/master/cupy/_environment.py). #6349
  - [x] Backport. #6422
- [ ] Documentation
  - [x] Add new wheel package to [Installation Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`. Update requirements in the installation guide. #6405
  - [x] Backport. #6543
  - [ ] Add new wheel package to the [website](https://cupy.dev). https://github.com/cupy/cupy.dev/pull/55
- [x] Implement or create an issue to support new features, if applicable.
- [x] Enable CUDA 11.6 test matrix in FlexCI https://github.com/cupy/cupy/pull/6553

**Comment by leofang** [comment]
CUDA Python 11.6 release note:
https://nvidia.github.io/cuda-python/release/11.6.0-notes.html#cuda-python-11-6-0-release-notes

**Comment by takagi** [comment]
No new compute capabilities are added to both nvcc and nvrtc.

**Comment by takagi** [comment]
Now no failures on my local.
```
= 97976 passed, 3963 skipped, 683 deselected, 88 xfailed, 1781 warnings in 11025.05s (3:03:45) =
```
