### ISSUE TITLE
Support ROCm 5.0

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#6459]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read [ROCm Release Notes](https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html).
- [x] Add FlexCI configuration for the ROCm version. #6466 #6496
- Wheel distribution
  - [x] Update cupy-release-tools. https://github.com/cupy/cupy-release-tools/pull/237
  - [x] Add the package to [duplicate detection](https://github.com/cupy/cupy/blob/master/cupy/_environment.py). #6466
  - [x] Backport. #6496
- Documentation
  - [x] Add new wheel package to [Installation Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`.  Update requirements in the installation guide. #6530
  - [x] Backport. #6607
  - [x] Add new wheel package to the [website](https://cupy.dev). https://github.com/cupy/cupy.dev/pull/54
- [x] Implement or create an issue to support new features, if applicable.

**Comment by takagi** [comment]
The half float representation issue which we were facing on ROCm 4.5 looks gone. With the change in #6466, I'm running CuPy's test locally.

**Comment by takagi** [comment]
ROCm 5.0.1 is out.

**Comment by takagi** [comment]
Looks cumsum doesn't work well and causes some of the CI errors including `test_dlpack.py`:
```
$ python -c 'import cupy; print(cupy.cumsum(cupy.array([0,0])))'
[                  0 1304722626565153334]
```

**Comment by takagi** [comment]
The way discussed in #4366 goes wrong on ROCm 5.0?
