### ISSUE TITLE
Support CUDA 11.6.2

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#6500]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read [CUDA Release Notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html).
- [x] Update CUDA driver in FlexCI images (Linux/Windows) (ask @kmaehashi).
- FlexCI
  - [ ] Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml` #6537
  - [ ] Backport.
- Compute Capability Support
  - [x] Check [NVRTC Reference (--gpu-architecture option)](https://docs.nvidia.com/cuda/nvrtc/index.html#group__options) and [NVCC Reference (--generate-code)](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-steering-gpu-code-generation-generate-code), and if needed, change the maximum value of supported compute capability defined in [cupy/cuda/compiler.py](https://github.com/cupy/cupy/blob/master/cupy/cuda/compiler.py) (`_nvrtc_max_compute_capability`) and `_cc_major_map` in `cupy/fft/_callback.pyx`. Also update the list of architectures in [cupy_setup_build.py](https://github.com/cupy/cupy/blob/master/install/cupy_builder/cupy_setup_build.py) (`_arch_list`).
  - [x] Backport.
- FP16 Headers
  - [x] Copy FP16 header files to `cupy/_core/include/cupy/_cuda/`, then update `cupy/_core/core.pyx` to use it.
  - [x] Backport.
- Library Installer
  - [x] Update `cupyx/tools/install_library.py`.
  - [x] Backport.
- Wheel Distribution
  - [ ] Update cupy-release-tools.
  - [ ] Backport.
- Wheel Package Detection
  - [x] Add the package to the [duplicate detection](https://github.com/cupy/cupy/blob/master/cupy/_environment.py).
  - [x] Backport.
- Documentation
  - [x] Add new wheel package to the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`. Update requirements in the installation guide.
  - [x] Backport.
  - [x] Add new wheel package to the [website](https://cupy.dev).
- [x] Implement or create an issue to support new features, if applicable.

**Comment by takagi** [comment]
Only a few things to do based on CUDA 11.6.0.

**Comment by kmaehashi** [comment]
CUDA 11.6.2 is also out.
