### ISSUE TITLE
Support NCCL 2.12

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#6521]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuSPARSELt](https://docs.nvidia.com/cuda/cusparselt/release_notes.html) / [cuDNN](https://docs.nvidia.com/deeplearning/cudnn/release-notes/index.html) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- FlexCI
  - [ ] Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml` #6534
  - [ ] Backport.
- Library Installer
  - [ ] Update `cupyx/tools/install_library.py`. #6534
  - [ ] Backport.
- Documentation
  - [ ] Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) #6534
  - [ ] Backport.
- [x] Implement new features using the version, if any.

**Comment by takagi** [comment]
No additional things in the header files.
