### ISSUE TITLE
Support ROCm 5.0.2

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#6529]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read [ROCm Release Notes](https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html).
- [x] Update AMD driver in Jenkins test infrastructure (ask @kmaehashi).
- FlexCI
  - [ ] Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml`
  - [ ] Backport.
- Wheel Distribution
  - [ ] Update cupy-release-tools.
  - [ ] Backport.
  - [ ] Update Jenkins job configuration for ROCm wheel build (`other_cupy_release_builder`) (ask @kmaehashi)
- Wheel Package Detection
  - [x] Add the package to the [duplicate detection](https://github.com/cupy/cupy/blob/master/cupy/_environment.py).
  - [x] Backport.
- Documentation
  - [x] Add new wheel package to the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`. Update requirements in the installation guide.
  - [x] Backport.
  - [x] Add new wheel package to the [website](https://cupy.dev).
- [x] Implement or create an issue to support new features, if applicable.

**Comment by takagi** [comment]
Basically nothing todo with ROCm 5.0.2, waiting for the official docker image of 5.0.2 that is not released yet.

**Comment by kmaehashi** [comment]
I guess it's unlikely that 5.0.2 docker images will be published as 5.1 is already shipped, so there's nothing we have to do.
