### ISSUE TITLE
Support ROCm 5.1

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#6606]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [ ] Read [ROCm Release Notes](https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html).
- [ ] Update AMD driver in Jenkins test infrastructure (ask @kmaehashi).
- FlexCI
  - [ ] Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml`
  - [ ] Backport.
- Wheel Distribution
  - [ ] Update cupy-release-tools.
  - [ ] Backport.
  - [ ] Update Jenkins job configuration for ROCm wheel build (`other_cupy_release_builder`) (ask @kmaehashi)
- Wheel Package Detection
  - [ ] Add the package to the [duplicate detection](https://github.com/cupy/cupy/blob/master/cupy/_environment.py).
  - [ ] Backport.
- Documentation
  - [ ] Add new wheel package to the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`. Update requirements in the installation guide.
  - [ ] Backport.
  - [ ] Add new wheel package to the [website](https://cupy.dev).
- [ ] Implement or create an issue to support new features, if applicable.

**Comment by takagi** [comment]
ROCm 5.1.1 is out.

**Comment by kmaehashi** [comment]
Now ROCm 5.1.3 is out.

**Comment by takagi** [comment]
Close as ROCm 5.2 is out. #6835.

**Comment by kmaehashi** [comment]
I think it's ok to skip 5.1 support, we can revisit if there are any demands.

**Comment by kmaehashi** [comment]
xref #6828
