### ISSUE TITLE
Support cuDNN 8.4

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#6623]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuSPARSELt](https://docs.nvidia.com/cuda/cusparselt/release_notes.html) / [cuDNN](https://docs.nvidia.com/deeplearning/cudnn/release-notes/index.html) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- FlexCI
  - [x] Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml` #6641
  - [ ] Backport.
- Library Installer
  - [x] Update `cupyx/tools/install_library.py`. #6641
  - [ ] Backport.
- Documentation
  - [x] Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) #6641
  - [ ] Backport.
- [x] Implement new features using the version, if any.

**Comment by takagi** [comment]
Took a diff to v8.3.2 header files, and all changes are ones related to cuDNN backend API.

**Comment by takagi** [comment]
Close as v11 is out and no backport is needed anymore.
