### ISSUE TITLE
Support cuTENSOR 1.5.0

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#6656]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuSPARSELt](https://docs.nvidia.com/cuda/cusparselt/release_notes.html) / [cuDNN](https://docs.nvidia.com/deeplearning/cudnn/release-notes/index.html) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- FlexCI
  - [x] Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml` #6665
  - [x] Backport. #6722
- Library Installer
  - [x] Update `cupyx/tools/install_library.py`. #6665
  - [x] Backport. #6722
- Documentation
  - [x] Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) #6665
  - [x] Backport. #6722
- [x] Implement new features using the version, if any. #6665

**Comment by leofang** [comment]
I think https://github.com/cupy/cupy/pull/6665 closes this 🙂
