### ISSUE TITLE
Support CUDA 11.7

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#6717]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read [CUDA Release Notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html).
- [x] Update CUDA driver in FlexCI images (Linux/Windows) (ask @kmaehashi).
- FlexCI
  - [x] Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml` #6767 
  - [x] Backport. #6794
- Compute Capability Support
  - [x] Check [NVRTC Reference (--gpu-architecture option)](https://docs.nvidia.com/cuda/nvrtc/index.html#group__options) and [NVCC Reference (--generate-code)](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-steering-gpu-code-generation-generate-code), and if needed, change the maximum value of supported compute capability defined in [cupy/cuda/compiler.py](https://github.com/cupy/cupy/blob/master/cupy/cuda/compiler.py) (`_nvrtc_max_compute_capability`) and `_cc_major_map` in `cupy/fft/_callback.pyx`. Also update the list of architectures in [_compiler.py](https://github.com/cupy/cupy/blob/master/install/cupy_builder/_compiler.py) (`arch_list`).
  - [x] Backport. #6794
- FP16 Headers
  - [x] Copy FP16 header files to `cupy/_core/include/cupy/_cuda/`, then update `cupy/_core/core.pyx` to use it. #6767
  - [x] Backport. #6794
- Library Installer
  - [x] Update `cupyx/tools/install_library.py`. #6767
  - [x] Backport. #6794
- Wheel Distribution
  - [x] Update cupy-release-tools. https://github.com/cupy/cupy-release-tools/pull/257
  - [x] Backport. https://github.com/cupy/cupy-release-tools/pull/270
- Wheel Package Detection
  - [x] Add the package to the [duplicate detection](https://github.com/cupy/cupy/blob/master/cupy/_environment.py). #6767
  - [x] Backport. #6794
- Universal Wheel Package (`cupy-wheel`)
  - [x] Update the list of packages in [universal_pkg](https://github.com/cupy/cupy/blob/master/install/universal_pkg/setup.py) #6767
  - [x] Backport. #6794
- Documentation
  - [x] Add new wheel package to the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`. Update requirements in the installation guide. #6768
  - [x] Backport. #6801
  - [ ] Add new wheel package to the [website](https://cupy.dev). https://github.com/cupy/cupy.dev/pull/57
- [x] Implement or create an issue to support new features, if applicable.

**Comment by kmaehashi** [comment]
Done! :tada:
Will merge https://github.com/cupy/cupy.dev/pull/57 after release.
