### ISSUE TITLE
Support cuSPARSELt v0.6.0

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#6757]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuSPARSELt](https://docs.nvidia.com/cuda/cusparselt/release_notes.html) / [cuDNN](https://docs.nvidia.com/deeplearning/cudnn/release-notes/index.html) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- FlexCI
  - [x] Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml`
  - [ ] ~Backport.~
- Library Installer
  - (n/a) Update `cupyx/tools/install_library.py`.
  - (n/a) ~Backport.~
- Documentation
  - [x] Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html)
  - [ ] ~Backport.~
- [x] Implement new features using the version, if any.

**Comment by leofang** [comment]
There is an API breaking change, see the release note.

**Comment by takagi** [comment]
Thanks for sharing!

**Comment by gdaisukesuzuki** [comment]
Excuse me, I'm an outsider. There seems to be no progress on this ISSUE.The following is a dirty patch, but I'll share it with you as I think it will probably work (I checked it with matmul.py placed under example).

```

*** cupy/cupy_backends/cuda/libs/cusparselt.pyx-dist    2022-06-06 22:13:35.118163775 +0900
--- cupy/cupy_backends/cuda/libs/cusparselt.pyx 2022-06-06 22:31:28.290615626 +0900
***************
*** 98,104 ****
          const void* data, size_t ataSize)
      cusparseStatus_t cusparseLtMatmulGetWorkspace(
          const cusparseLtHandle_t* handle,
!         const cusparseLtMatmulAlgSelection_t* algSelection,
          size_t* workspaceSize)
      cusparseStatus_t cusparseLtMatmulPlanInit(
          const cusparseLtHandle_t* handle,
--- 98,104 ----
          const void* data, size_t ataSize)
      cusparseStatus_t cusparseLtMatmulGetWorkspace(
          const cusparseLtHandle_t* handle,
!         const cusparseLtMatmulPlan_t* plan,
          size_t* workspaceSize)
      cusparseStatus_t cusparseLtMatmulPlanInit(
          const cusparseLtHandle_t* handle,
***************
*** 371,382 ****
      check_status(status)
  
  cpdef size_t matmulGetWorkspace(Handle handle,
!                                 MatmulAlgSelection algSelection):
      """Determines the required workspace size"""
      cdef size_t workspaceSize
      status = cusparseLtMatmulGetWorkspace(
          <const cusparseLtHandle_t*> handle._ptr,
!         <const cusparseLtMatmulAlgSelection_t*> algSelection._ptr,
          &workspaceSize)
      check_status(status)
      return workspaceSize
--- 371,382 ----
      check_status(status)
  
  cpdef size_t matmulGetWorkspace(Handle handle,
!                                 MatmulPlan plan):
      """Determines the required workspace size"""
      cdef size_t workspaceSize
      status = cusparseLtMatmulGetWorkspace(
          <const cusparseLtHandle_t*> handle._ptr,
!         <const cusparseLtMatmulPlan_t*> plan._ptr,
          &workspaceSize)
      check_status(status)
      return workspaceSize
*** cupy/cupy_backends/cuda/libs/cusparselt.pxd-dist    2022-06-28 17:49:01.098110960 +0900
--- cupy/cupy_backends/cuda/libs/cusparselt.pxd 2022-06-28 17:55:35.049725677 +0900
***************
*** 23,30 ****
      CUSPARSELT_MATMUL_ACTIVATION_RELU_UPPERBOUND = 1  # READ/WRITE
      CUSPARSELT_MATMUL_ACTIVATION_RELU_THRESHOLD = 2   # READ/WRITE
      CUSPARSELT_MATMUL_ACTIVATION_GELU = 3             # READ/WRITE
!     CUSPARSELT_MATMUL_BIAS_STRIDE = 4                 # READ/WRITE
!     CUSPARSELT_MATMUL_BIAS_POINTER = 5                # READ/WRITE
  
      # cusparseLtMatmulAlg_t
      CUSPARSELT_MATMUL_ALG_DEFAULT = 0
--- 23,33 ----
      CUSPARSELT_MATMUL_ACTIVATION_RELU_UPPERBOUND = 1  # READ/WRITE
      CUSPARSELT_MATMUL_ACTIVATION_RELU_THRESHOLD = 2   # READ/WRITE
      CUSPARSELT_MATMUL_ACTIVATION_GELU = 3             # READ/WRITE
!     CUSPARSELT_MATMUL_ACTIVATION_GELU_SCALING = 4     # READ/WRITE
!     CUSPARSELT_MATMUL_ALPHA_VECTOR_SCALING = 5        # READ/WRITE
!     CUSPARSELT_MATMUL_BETA_VECTOR_SCALING = 6         # READ/WRITE
!     CUSPARSELT_MATMUL_BIAS_STRIDE = 7                 # READ/WRITE
!     CUSPARSELT_MATMUL_BIAS_POINTER = 8                # READ/WRITE
  
      # cusparseLtMatmulAlg_t
      CUSPARSELT_MATMUL_ALG_DEFAULT = 0
***************
*** 33,38 ****
--- 36,49 ----
      CUSPARSELT_MATMUL_ALG_CONFIG_ID = 0      # NOQA, READ/WRITE
      CUSPARSELT_MATMUL_ALG_CONFIG_MAX_ID = 1  # NOQA, READ-ONLY
      CUSPARSELT_MATMUL_SEARCH_ITERATIONS = 2  # NOQA, READ/WRITE
+     CUSPARSELT_MATMUL_SPLIT_K = 3            # NOQA, READ/WRITE
+     CUSPARSELT_MATMUL_SPLIT_K_MODE =4        # NOQA, READ/WRITE
+     CUSPARSELT_MATMUL_SPLIT_K_BUFFERS=5      # NOQA, READ/WRITE
+     
+     # cusparseLtSplitKMode_t
+     CUSPARSELT_INVALID_MODE             = 0
+     CUSPARSELT_SPLIT_K_MODE_ONE_KERNEL  = 1
+     CUSPARSELT_SPLIT_K_MODE_TWO_KERNELS = 2
  
      # cusparseLtPruneAlg_t
      CUSPARSELT_PRUNE_SPMMA_TILE = 0
*** cupy/examples/cusparselt/matmul.py-dist     2023-02-26 07:13:02.334317731 +0900
--- cupy/examples/cusparselt/matmul.py  2023-02-26 07:12:01.363764270 +0900
***************
*** 56,62 ****
  cusparselt.matmulAlgSetAttribute(handle, alg_sel,
                                   cusparselt.CUSPARSELT_MATMUL_ALG_CONFIG_ID,
                                   alg.ctypes.data, 4)
! workspace_size = cusparselt.matmulGetWorkspace(handle, alg_sel)
  workspace = cupy.empty(workspace_size, dtype='int8')
  cusparselt.matmulPlanInit(handle, plan, matmul, alg_sel, workspace_size)
  
--- 56,63 ----
  cusparselt.matmulAlgSetAttribute(handle, alg_sel,
                                   cusparselt.CUSPARSELT_MATMUL_ALG_CONFIG_ID,
                                   alg.ctypes.data, 4)
! # workspace_size = cusparselt.matmulGetWorkspace(handle, plan)
! workspace_size = 0
  workspace = cupy.empty(workspace_size, dtype='int8')
  cusparselt.matmulPlanInit(handle, plan, matmul, alg_sel, workspace_size)
  

```

**Comment by leofang** [comment]
FYI the v0.4.0 binary supports both CUDA 11 & 12 (https://github.com/conda-forge/cusparselt-feedstock/pull/26), so if CuPy updates to use v0.4.0 we can support CUDA 12 wheel/conda users too.

**Comment by gdaisukesuzuki** [comment]
Hi, @kmaehashi -san

Since there seems to be no progress on this ticket, I wrote a dirty patch myself to call cusparselt 5.0.2 on cupy. It worked as follows. Hope it helps.
[cupy_cusparselt5.patch](https://github.com/cupy/cupy/files/13799966/cupy_cusparselt5.patch)

```
>>> cupy.show_config()
OS                           : Linux-6.6.8-arch1-1-x86_64-with-glibc2.38
Python Version               : 3.11.6
CuPy Version                 : 13.0.0rc1
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.2
SciPy Version                : 1.11.4
Cython Build Version         : 0.29.36
Cython Runtime Version       : 0.29.37
CUDA Root                    : /opt/cuda
nvcc PATH                    : /opt/cuda/bin/nvcc
CUDA Build Version           : 12030
CUDA Driver Version          : 12030
CUDA Runtime Version         : 12030 (linked to CuPy) / 12030 (locally installed)
cuBLAS Version               : (available)
cuFFT Version                : 11012
cuRAND Version               : 10304
cuSOLVER Version             : (11, 5, 4)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 3)
Thrust Version               : 200200
CUB Build Version            : 200200
Jitify Build Version         : 2d02eaafe
cuDNN Build Version          : 8907
cuDNN Version                : 8907
NCCL Build Version           : 21904
NCCL Runtime Version         : 21904
cuTENSOR Version             : 20000
cuSPARSELt Build Version     : 502
Device 0 Name                : NVIDIA GeForce RTX 4080
Device 0 Compute Capability  : 89
Device 0 PCI Bus ID          : 0000:01:00.0
>>> exec(open("./matmul.py").read())
Before pruning, A[0]:
[0.711  0.4236 0.3054 ... 0.4932 0.8906 0.308 ]
After pruning, A[0]:
[0.711  0.4236 0.     ... 0.     0.8906 0.    ]
A.sum(axis=1): [339.  343.2 330.8 ... 334.5 340.5 346.2]
C[:, 0]: [338.8 343.2 330.8 ... 334.5 340.5 346.2]
>>>
```

**Comment by leofang** [comment]
@gdaisukesuzuki please feel free to submit a PR! 🙂

Note that starting v0.5.0 only CUDA 12 is supported.

**Comment by gdaisukesuzuki** [comment]
@leofang -san
I sent PR . As you know, it is only compatible with CUDA12 + cusparseLt 0.5.2 (not 0.5.0).

**Comment by gdaisukesuzuki** [comment]
I have updated the PR from compatibility with cusparselt 0.5.2 to compatibility with cusparselt 0.6.0.

**Comment by gdaisukesuzuki** [comment]
@kmaehashi 

Change the title of this issue from 0.5.0 to 0.6.0, please.

**Comment by gdaisukesuzuki** [comment]
@kmaehashi Thank you for merging the PR #8074 . However, I left some documentation not updated. Please check the PR #8362 again.

**Comment by gdaisukesuzuki** [comment]
@kmaehashi If you afford to, check #8364, please.
