### ISSUE TITLE
Support NumPy 1.23

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#6764]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes.
- [x] #6807
- FlexCI
  - [x] Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml` if needed. #6820
  - [ ] Backport.
- Update Requirements (for NumPy/SciPy)
  - [x] Bump the pinned minimum/maximum version in `setup.py` (see #4773.) #6820
  - [ ] Backport.
- Documentation
  - [x] Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) (note: the baseline version must be updated only in the development branch). Also update `docs/requirements.txt` to use the latest versions. #6820
  - [ ] Backport.

----

Test with NumPy 1.23rc2 failing:
https://ci.preferred.jp/cupy.linux.cuda-head/103003/
https://ci.preferred.jp/cupy.linux.cuda-head-stable/103006/

**Comment by kmaehashi** [comment]
https://numpy.org/devdocs/release/1.23.0-notes.html

Things that may be affected:

* Changing to dtype of a different size now requires contiguity of only the last axis
* keepdims parameter for average
* New parameter equal_nan added to np.unique
* 1D np.linalg.norm preserves float input types, even for scalar results

**Comment by kmaehashi** [comment]
Adding this one to rc milestone.

**Comment by kmaehashi** [comment]
> As we are about to v11 branch cut, I think it's ok not to backport NumPy 1.23 things to v10. Even without the "official" support, users can safely use NumPy 1.23 + CuPy v10.

Discussed offline and agreed with this.
