### ISSUE TITLE
Support SciPy 1.9

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#6957]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes.
- FlexCI
  - [x] Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml` if needed. #6962
  - [x] Backport. #6981
- Update Requirements (for NumPy/SciPy)
  - [x] Bump the pinned minimum/maximum version in `setup.py` (see #4773.) #6962
  - [x] Backport. #6981
- Documentation
  - [x] Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) (note: the baseline version must be updated only in the development branch). Also update `docs/requirements.txt` to use the latest versions. #6962
  - [x] Backport. #6981
- [x] Apply fixes needed to follow the specification changes.

**Comment by takagi** [comment]
Rel. https://github.com/cupy/cupy/pull/6961
