### ISSUE TITLE
Support cuDNN 8.5

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#6983]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuSPARSELt](https://docs.nvidia.com/cuda/cusparselt/release_notes.html) / [cuDNN](https://docs.nvidia.com/deeplearning/cudnn/release-notes/index.html) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- FlexCI
  - [x] Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml` #7008
  - [x] Backport.
- Library Installer
  - [x] Update `cupyx/tools/install_library.py`. #7008
  - [x] Backport.
- Documentation
  - [x] Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) #7008
  - [x] Backport.
- [x] Implement new features using the version, if any.
