### ISSUE TITLE
Support CUDA 11.8

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#7080]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read [CUDA Release Notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html).
- [x] Update CUDA driver in FlexCI images (Linux/Windows) (ask @kmaehashi).
- [x] Fix code and CI to support the new vesrion. #7117
  - **FlexCI**: Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml`
  - **Compute Capability Support**: Check [NVRTC Reference (--gpu-architecture option)](https://docs.nvidia.com/cuda/nvrtc/index.html#group__options) and [NVCC Reference (--generate-code)](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-steering-gpu-code-generation-generate-code), and if needed, change the maximum value of supported compute capability defined in [cupy/cuda/compiler.py](https://github.com/cupy/cupy/blob/master/cupy/cuda/compiler.py) (`_nvrtc_max_compute_capability`) and `_cc_major_map` in `cupy/fft/_callback.pyx`. Also update the list of architectures in [_compiler.py](https://github.com/cupy/cupy/blob/master/install/cupy_builder/_compiler.py) (`arch_list`).
  - **FP16 Headers**: Copy FP16 header files to `cupy/_core/include/cupy/_cuda/`, then update `cupy/_core/core.pyx` to use it.
  - **Library Installer**: Update `cupyx/tools/install_library.py`.
  - **Wheel Package Detection**: Add the package to the [duplicate detection](https://github.com/cupy/cupy/blob/master/cupy/_environment.py).
  - **Universal Wheel Package (`cupy-wheel`)**: Update the list of packages and detection logic in [universal_pkg](https://github.com/cupy/cupy/blob/master/install/universal_pkg/setup.py)
- [x] Backport the above PR. #7134 
- [x] Fix cupy-release-tools to support the new version. https://github.com/cupy/cupy-release-tools/pull/302
- [x] Backport the above PR. https://github.com/cupy/cupy-release-tools/pull/306
- [x] Fix documentation. #7119
  - Add new wheel package to the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`.
  - Update requirements in the installation guide.
- [x] Backport the above PR. #7148
- [x] Add new wheel package to the [website](https://cupy.dev).
- [x] Implement or create an issue to support new features, if applicable. #7100 #7169

**Comment by leofang** [comment]
Need to support sm89 & sm90.

**Comment by takagi** [comment]
Close as done.
