### ISSUE TITLE
Support NCCL 2.15

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7094]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuSPARSELt](https://docs.nvidia.com/cuda/cusparselt/release_notes.html) / [cuDNN](https://docs.nvidia.com/deeplearning/cudnn/release-notes/index.html) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- [x] Fix code and CI to support the new version. #7117 #7153
  - **FlexCI**: Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml`.
  - **Library Installer**: Update `cupyx/tools/install_library.py`.
- [x] Backport the above PR. #7134 #7160
- [x] Fix documentation. #7117
  - Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html)
- [x] Backport the above PR. #713
- [x] Implement new features using the version, if any.

**Comment by kmaehashi** [comment]
@takagi Let me assign this to you as a part of CUDA 11.8 support :pray:

**Comment by kmaehashi** [comment]
> Read Release Notes

NCCL 2.15 adds support for H100 (sm90).
