### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7142]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes
- [x] Ask fastrlock to release wheels (e.g., https://github.com/scoder/fastrlock/issues/11)
- [x] Fix code and CI to support the new vesrion. #7159
  - **FlexCI**: Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml` (note: Some Python libraries may not be supported with the newer versions of Python. In that case you should also limit the library version.)
  - **Package Metadata**: Update package classifier and `python_requires` tag (if needed) in `setup.py`.
- [x] Backport the above PR. #7179
- [x] Fix `cupy-release-tools` to support the new version. https://github.com/cupy/cupy-release-tools/pull/305
- [x] Backport the above PR. https://github.com/cupy/cupy-release-tools/pull/307
- [x] Update Jenkins job configuration for ROCm wheel build (`other_cupy_release_builder`) (ask @kmaehashi)
- [x] Fix documentation. #7159
  - Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html)
- [x] Backport the above PR. #7179
