### ISSUE TITLE
Support cuDNN 8.7

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7212]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuSPARSELt](https://docs.nvidia.com/cuda/cusparselt/release_notes.html) / [cuDNN](https://docs.nvidia.com/deeplearning/cudnn/release-notes/index.html) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- [x] Fix code and CI to support the new version. #7285
  - **FlexCI**: Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml`.
  - **Library Installer**: Update `cupyx/tools/install_library.py`.
- [x] Backport the above PR. #7296
- [x] Fix documentation. #7310 
  - Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html)
- [x] Backport the above PR. #7320
- [x] Implement new features using the version, if any. -> n/a
