### ISSUE TITLE
Support ROCm 5.6

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#7217]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [ ] Read [ROCm Release Notes](https://docs.amd.com/).
- [ ] Update AMD driver in Jenkins test infrastructure (ask @kmaehashi).
- [ ] Fix code and CI to support the new vesrion.
  - **FlexCI**: Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml`.
  - **Wheel Package Detection**: Add the package to the [duplicate detection](https://github.com/cupy/cupy/blob/master/cupy/_environment.py).
  - **Universal Wheel Package (`cupy-wheel`)**: Update the list of packages and detection logic in [universal_pkg](https://github.com/cupy/cupy/blob/master/install/universal_pkg/setup.py).
- [ ] Backport the above PR.
- [ ] Update Jenkins job configuration for ROCm wheel build (`other_cupy_release_builder`) (ask @kmaehashi)
- [ ] Fix `cupy-release-tools` to support the new version.
- [ ] Backport the above PR.
- [ ] Fix documentation.
  - Add new wheel package to the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`.
  - Update requirements in the installation guide.
- [ ] Backport the above PR.
- [ ] Add new wheel package to the [website](https://cupy.dev).
- [ ] Implement or create an issue to support new features, if applicable.

**Comment by LakshmiKumar23** [comment]
@takagi @amathews-amd Do we know when this will be available? Does it support rocm5.3 in the meantime?

**Comment by amathews-amd** [comment]
Hi @LakshmiKumar23 , I see you work for AMD. please reach out to me internally, and we can find a solution for you.

**Comment by kmaehashi** [comment]
Sorry for this issue being in a task queue for a long time. Thanks to #7079, basic functionality should work fine with ROCm 5.3. CIs for several functions (such as `cupyx.scipy.ndimage`) are failing (look for `FAILED` in the test log attached) and need to be investigated.
[consoleText.txt](https://github.com/cupy/cupy/files/10515373/consoleText.txt)

**Comment by kmaehashi** [comment]
ROCm 5.5 is out, updated the title.

**Comment by kmaehashi** [comment]
ROCm 5.6 is out

**Comment by kmaehashi** [comment]
We will skip ROCm 5.x support and directly jump to 6.2. #8606
