### ISSUE TITLE
Support CUDA 12.0

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#7232]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read [CUDA Release Notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html).
- [x] Update CUDA driver in FlexCI images (Linux/Windows) (ask @kmaehashi).
- [x] Fix code and CI to support the new version. (**SEE LIST BELOW**)
  - [x] **FlexCI**: Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml`.
  - [x] **Compute Capability Support**: Check [NVRTC Reference (--gpu-architecture option)](https://docs.nvidia.com/cuda/nvrtc/index.html#group__options) and [NVCC Reference (--generate-code)](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-steering-gpu-code-generation-generate-code), and if needed, change the maximum value of supported compute capability defined in [cupy/cuda/compiler.py](https://github.com/cupy/cupy/blob/master/cupy/cuda/compiler.py) (`nvrtc_max_compute_capability`) and `_cc_major_map` in `cupy/fft/_callback.pyx`. Also update the list of architectures in [_compiler.py](https://github.com/cupy/cupy/blob/master/install/cupy_builder/_compiler.py) (`arch_list`).
  - [x] **FP16 Headers**: Copy FP16 header files to `cupy/_core/include/cupy/_cuda/`, then update `cupy/_core/core.pyx` to use it.
  - [x] **Library Installer**: Update `cupyx/tools/install_library.py`.
  - [x] **Wheel Package Detection**: Add the package to the [duplicate detection](https://github.com/cupy/cupy/blob/master/cupy/_environment.py).
  - [x] **Universal Wheel Package (`cupy-wheel`)**: Update the list of packages and detection logic in [universal_pkg](https://github.com/cupy/cupy/blob/master/install/universal_pkg/setup.py)
- [x] Backport the above PR.
- [x] Fix `cupy-release-tools` to support the new version.  https://github.com/cupy/cupy-release-tools/pull/322
- [x] Backport the above PR. https://github.com/cupy/cupy-release-tools/pull/325
- [x] Fix documentation.
  - Add new wheel package to the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`.
  - Update requirements in the installation guide.
- [x] Backport the above PR.
- [x] Add new wheel package to the [website](https://cupy.dev). https://github.com/cupy/cupy.dev/pull/61
- [x] Implement or create an issue to support new features, if applicable.

Pull-requests / backports:
- #7235 / #7238
- #7236 / #7257
- #7237 / #7241
- #7283 / #7288
- #7284 / #7290
- #7285 / #7296
- #7298 / #7301
- #7299 / #7317
- #7300 / #7327
- #7310 / #7320

**Comment by leofang** [comment]
cc: @anaruse

**Comment by kmaehashi** [comment]
TODO: Emit DeprecationWarning in these APIs to plan removal in CuPy
* https://docs.cupy.dev/en/latest/reference/generated/cupy.cuda.texture.TextureReference.html
* https://docs.cupy.dev/en/latest/reference/generated/cupy.cuda.profiler.initialize.html
