### ISSUE TITLE
Support SciPy 1.10

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7273]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes.
- [x] Fix code and CI to support the new vesrion.
  - **FlexCI**: Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml`.
  - **Update Requirements**: For NumPy/SciPy, bump the pinned minimum/maximum version in `setup.py` (see #4773.)
- [x] Backport the above PR.
- [x] Fix documentation.
  - Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) (note: the baseline version must be updated only in the development branch).
  - Update `docs/requirements.txt` to use the latest versions.
- [x] Backport the above PR.
- [x] Apply fixes needed to follow the specification changes.

**Comment by kmaehashi** [comment]
Done via #7367
