### ISSUE TITLE
Support NCCL 2.16

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7282]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuSPARSELt](https://docs.nvidia.com/cuda/cusparselt/release_notes.html) / [cuDNN](https://docs.nvidia.com/deeplearning/cudnn/release-notes/index.html) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- [x] Fix code and CI to support the new version. #7283
  - **FlexCI**: Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml`.
  - **Library Installer**: Update `cupyx/tools/install_library.py`.
- [x] Backport the above PR. #7288
- [ ] Fix documentation. #7310
  - Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html)
- [ ] Backport the above PR.
- [ ] Implement new features using the version, if any.
