### ISSUE TITLE
Support CUDA 12.1

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7441]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [ ] Read [CUDA Release Notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html).
- [ ] Update CUDA driver in FlexCI Windows image (ask @kmaehashi).
- [ ] Fix code and CI to support the new vesrion.
  - **FlexCI**: Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml`.
  - **Compute Capability Support**: Check [NVRTC Reference (--gpu-architecture option)](https://docs.nvidia.com/cuda/nvrtc/index.html#group__options) and [NVCC Reference (--generate-code)](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-steering-gpu-code-generation-generate-code), and if needed, change the maximum value of supported compute capability defined in [cupy/cuda/compiler.py](https://github.com/cupy/cupy/blob/master/cupy/cuda/compiler.py) (`nvrtc_max_compute_capability`) and `_cc_major_map` in `cupy/fft/_callback.pyx`. Also update the list of architectures in [_compiler.py](https://github.com/cupy/cupy/blob/master/install/cupy_builder/_compiler.py) (`arch_list`).
  - **FP16 Headers**: Copy FP16 header files to `cupy/_core/include/cupy/_cuda/`, then update `cupy/_core/core.pyx` to use it.
  - **Library Installer**: Update `cupyx/tools/install_library.py`.
  - **Wheel Package Detection**: Add the package to the [duplicate detection](https://github.com/cupy/cupy/blob/master/cupy/_environment.py).
  - **Universal Wheel Package (`cupy-wheel`)**: Update the list of packages and detection logic in [universal_pkg](https://github.com/cupy/cupy/blob/master/install/universal_pkg/setup.py)
- [ ] Backport the above PR.
- [ ] Fix `cupy-release-tools` to support the new version.
- [ ] Backport the above PR.
- [ ] Fix documentation.
  - Add new wheel package to the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) and `README.md`.
  - Update requirements in the installation guide.
- [ ] Backport the above PR.
- [ ] Add new wheel package to the [website](https://cupy.dev).
- [ ] Implement or create an issue to support new features, if applicable.
