### ISSUE TITLE
Support NCCL 2.18.1

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7542]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuSPARSELt](https://docs.nvidia.com/cuda/cusparselt/release_notes.html) / [cuDNN](https://docs.nvidia.com/deeplearning/cudnn/release-notes/index.html) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- [ ] Fix code and CI to support the new vesrion.
  - **FlexCI**: Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml`.
  - **Library Installer**: Update `cupyx/tools/install_library.py`.
- [ ] Backport the above PR.
- [ ] Fix documentation.
  - Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html)
- [ ] Backport the above PR.
- [ ] Implement new features using the version, if any.

**Comment by kmaehashi** [comment]
CI will be added in #7748
