### ISSUE TITLE
CuPy v13 Release Plan

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7555]
## Roadmap

```[tasklist]
## Planned Features

- [ ] Signal API coverage enhancement (`cupyx.scipy.signal.*`)
- [ ] `complex32` support for limited APIs (restart #4454)
- [ ] Support reduction ops in distrubuted ndarray
- [ ] Allow `import cupy` without CUDA installation (#6908)
- [ ] Migrate from Thurst/CUB to [CCCL](https://github.com/NVIDIA/cccl)
- [ ] Typed CuPy APIs (#4831)
- [ ] Memory allocator interoperability with PyTorch (to be discussed in a separate issue)
- [ ] Drop support for CUDA 10.2, 11.0, and 11.1 (to be discussed in a separate issue)
- [ ] Support Python 3.12 (both in CuPy v12 and v13)
- [ ] Drop support for Python 3.9 following [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html)
- [ ] Release workflow improvement: GitHub Action-based wheel build (https://github.com/cupy/cupy-release-tools/issues/272#issuecomment-1165093812)
```

```[tasklist]
## Timeline & Release Manager
- [ ] **v13.0.0a1 (v12.1.0)** (May 2023) @takagi
- [ ] **v13.0.0b1 (v12.2.0)** (July 2023) @kmaehashi
- [ ] **v13.0.0rc1 (v12.3.0)** (September 2023) @asi1024
- [ ] **v13.0.0** (October 2023) @emcastillo
```

## Notes

* As of CuPy v13, we have adjusted our release frequency to once every two months. However, mid-term or hot-fix releases may be provided depending on necessity, such as for new CUDA/Python version support or critical bug fixes.
* The schedule and planned features may be subject to change depending on the progress of the development.
* `v12.x` releases will only contain backported pull-requests (mainly bug-fixes) from the v13 (`main`) branch.

## Past Release Plans

* v9: https://github.com/cupy/cupy/issues/3891
* v10: https://github.com/cupy/cupy/issues/5049
* v11: https://github.com/cupy/cupy/issues/6246
* v12: https://github.com/cupy/cupy/issues/6866

**Comment by leofang** [comment]
> Drop support for Python 3.9 following [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html)

I think you meant 3.8, not 3.9? 🙂

**Comment by kmaehashi** [comment]
Absolutely! Fixed.

**Comment by jakirkham** [comment]
Regarding 13.3.0, we would like to do some testing with @seberg's recent fixes

Also trying to see if these SciPy issues are resolved:

* https://github.com/scipy/scipy/issues/21227
* https://github.com/scipy/scipy/issues/21228

We are building some test packages to aid this work in PR:

* https://github.com/conda-forge/cupy-feedstock/pull/272

**Comment by leofang** [comment]
I need this PR to be included in v13.3.0 too: https://github.com/cupy/cupy/pull/8412. Thanks.

**Comment by jakirkham** [comment]
This looks potentially easy to get in. Just need CI running

* https://github.com/cupy/cupy/pull/8441

**Comment by jakirkham** [comment]
As to testing, Lucas from SciPy helped us test CuPy 13.3.0 dev packages and they are looking good: https://github.com/scipy/scipy/issues/20957#issuecomment-2263541811

Sebastian, Greg, and other RAPIDS folks have been helping test and integrate minor RAPIDS-side fixes. Generally things are looking good there

So I think if we can round out the last couple changes above, maybe would be in a good spot to release 13.3.0. Would be interested to hear what other folks are thinking?

**Comment by kmaehashi** [comment]
I'm thinking of including the following PRs in the v13.3.0 release (planned sometime this month). Let me know if you need other PRs to be in!

* PRs in [v14.0.0a1 milestone](https://github.com/cupy/cupy/milestone/147) with `to-be-backported` label
* PRs in [v13.3.0 milestone](https://github.com/cupy/cupy/milestone/151)

**Comment by jakirkham** [comment]
Also would be good to recheck this issue and confirm whether it can be closed:

* https://github.com/cupy/cupy/issues/7796

Believe this was fixed and backported to v13 already in this PR

* https://github.com/cupy/cupy/pull/8357

**Comment by jakirkham** [comment]
Once those are done. Think we are ready to go from the RAPIDS side

**Comment by jakirkham** [comment]
From a RAPIDS perspective, think 13.3.0 is ready to go

Not sure what others' thoughts are

**Comment by jakirkham** [comment]
After some more testing, think we need a fix for issue ( https://github.com/cupy/cupy/issues/8466 ) for conda. Started PR: https://github.com/cupy/cupy/pull/8519

**Comment by jakirkham** [comment]
JFYI ran into a build issue in the past 24hrs. Still investigating atm. Mentioning here for awareness

Tracking issue: https://github.com/cupy/cupy/issues/8541

**Comment by jakirkham** [comment]
Would it be possible to backport this RBFInterpolator SciPy 1.13+ compatibility fix ( https://github.com/cupy/cupy/pull/8343 ) to CuPy 13.x?

**Comment by monzelr** [comment]
Bumping in here: Does anyone know when the next release of cupy will be released? I am currently having problems building cupy on my windows machine, so I am waiting for the next release. 👀

**Comment by kmaehashi** [comment]
We plan to ship v13.4.0 around the end of January!

**Comment by jkbchouinard** [comment]
Any updates on v13.4.0 release timing?

**Comment by kmaehashi** [comment]
CUDA 12.8 with Blackwell architecture support was released in January, so we are trying to include the support for it in the v13.4.0 release. I'm assuming the release will be around the end of this month.

**Comment by jakirkham** [comment]
Highlighting this fix that we would like in 13.4.0. It fixes a bug in unreleased 13.x code. So it would be nice to have it in before there is a release

* https://github.com/cupy/cupy/pull/8970

**Comment by kmaehashi** [comment]
We are finalizing on making stable v14 release (https://github.com/cupy/cupy/issues/8269#issuecomment-3413534515). Closing as no further v13 stable releases are planned.
