### ISSUE TITLE
Support NumPy 1.25 & 1.26

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7616]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes.
- [x] Fix code and CI to support the new vesrion.
  - **FlexCI**: Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml`. #7897
  - **Update Requirements**: For NumPy/SciPy, bump the pinned minimum/maximum version in `setup.py` (see #4773.) #7992
- [x] Backport the above PR. #8001, #7932
- [ ] For NumPy update, reflect the changes in `numpy.array_api` to `cupy.array_api`.
- [ ] Backport the above PR.
- [x] Fix documentation. #7992
  - Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) (note: the baseline version must be updated only in the development branch).
  - Update `docs/requirements.txt` to use the latest versions.
- [x] Backport the above PR. #8001
- [x] Apply fixes needed to follow the specification changes.

----

There are several deprecations in NumPy that we will be affected, e.g.:

```
00:58:26.329804 STDOUT 1326]	E       DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.	
00:58:26.329806 STDOUT 1326]	E       See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)	
```

Full test log with NumPy v1.25.0rc1: https://ci.preferred.jp/cupy.linux.cuda-head/133055/
NumPy release notes: https://github.com/numpy/numpy/releases/tag/v1.25.0rc1

**Comment by jakirkham** [comment]
cc @seberg (in case you have any thoughts here)

**Comment by seberg** [comment]
Not particularly, the `find_common_type` PR looks good already (stealing more for the `AxisConcatenator` from NumPy is probably better, though).  Some notes, to maybe clarify some larger changes:

* `inout` in `def __array_function__ ` should be expanded with ([change](https://numpy.org/devdocs/release/1.25.0-notes.html#array-likes-that-define-array-ufunc-can-now-override-ufuncs-if-used-as-where)):
  ```
  if 'where' in kwargs:
      inout += (kwargs["where"],)
  ```
* The `==`/`!=` doesn't affect cupy as it is irrelevant for numeric types.
* [Supporting `@=`](https://github.com/numpy/numpy/pull/21120) should be easier for cupy, I don't quite remember, but I think part of the problem was supporting `__array_ufunc__`.  The things to ensure is:
   * The second argument *must* be 2-D  (there is a custom error there)
   * `a = np.ones((1, 3)); b = np.ones((3, 1)); a @= b` should fail.  (The last two dimensions of `a` must be the same length the result, if `a` has one dimension, than that dimensions only of course).
   * (The numpy logic is trickier using `axes=` on the generalized ufunc, which is also a way to implement this.  I don't remember, but I suspect I only used it because the simpler solution interfered with `__array_ufunc__` dispatching, which probably doesn't matter for you.)

Happy to give a hand with the updates or review.

**Comment by kmaehashi** [comment]
NumPy 1.26b1 is out, and head CI says segfault:

https://ci.preferred.jp/cupy.linux.cuda-head-stable/142263/

```
00:30:25.307255 STDOUT 1325]	cupy_tests/indexing_tests/test_indexing.py ............................. [  9%]	
00:30:25.362302 STDOUT 1325]	..Fatal Python error: Segmentation fault	
00:30:25.362319 STDOUT 1325]		
00:30:25.362345 STDOUT 1325]	Current thread 0x00007ff9d3209740 (most recent call first):	
00:30:25.362453 STDOUT 1325]	  File "/tmp/tmp.aBJWPO65lF/tests/cupy_tests/indexing_tests/test_indexing.py", line 262 in test_choose_broadcast_fail	
```

**Comment by kmaehashi** [comment]
The segfault seems to be fixed in NumPy 1.26 official release 😃

**Comment by kmaehashi** [comment]
Track remaining tasks in #8008
