### ISSUE TITLE
Allow `import cupy` without CUDA installation

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7620]
Currently, `import cupy` requires the GPU toolkit (CUDA/ROCm) installed. However, several people reported this is cumbersome, especially when developing or running NumPy/CuPy agnostic code under a CPU-only machine.

This is a tracker issue to implement idea 2 discussed in the RFC pull-request (https://github.com/cupy/cupy/pull/6908#issuecomment-1196459041).

```[tasklist]
### Modules
- [x] NVRTC #7621
- [x] cuSOLVER (depends on cuBLAS and cuSPARSE) #7843
- [x] cuSPARSE #7847
- [x] cuFFT #7849
- [x] cuRAND #7856
- [x] cuBLAS #7921
- [x] CUB (depends on Runtime) #7850
- [x] Jitify (depends on NVRTC, Runtime, Driver) #7954
- [x] Runtime #7954
- [x] Profiler (part of Runtime) #7954
- [x] Implement `cupy.cuda.get_local_runtime_version()` to query CUDART version in user environment (#7954)
- [x] Driver #7994
- [x] Improve `cupy.show_config()` to show local runtime version #7995
- [ ] Add CI to make sure `import cupy` succeeds without CUDA Toolkit #7996
```

**Comment by leofang** [comment]
Hi @kmaehashi I'd like to double check one design decision here. @pentschev told me that the current design intends to fail all GPU computation if any of the dlopen (via SoftLink) fails. This is quite surprising to me, because the way we did dlopen to support deferred import and missing libraries should work for a partial CTK. That is, if some DSOs are missing, the function pointers from those DSOs would be `None`, but that's all. The rest of the stack should still work as long as other needed DSOs are there. 
 
For example, if `libcufft.so` is missing, it's natural to expect all `cupy.fft.*` functions stop working, but other functions, say `cupy.matmul()` or `cupy.sin()`, should continue working (the former needs cuBLAS, the latter needs NVRTC). Is this understanding correct?

Asking because there are Jetson users who can only afford a partial CTK installation. Also, conda-forge's new layout naturally supports partial installation, too.

**Comment by kmaehashi** [comment]
> For example, if `libcufft.so` is missing, it's natural to expect all `cupy.fft.*` functions stop working, but other functions, say `cupy.matmul()` or `cupy.sin()`, should continue working (the former needs cuBLAS, the latter needs NVRTC). Is this understanding correct?

I had a discussion with Peter in the offline meeting last month and agreed to go with this behavior, i.e., even if a part of CTK libraries is missing, CuPy functionalities that do not use that library will work. 😃

**Comment by leofang** [comment]
Nice, thanks for clarification, Kenichi-san!

**Comment by leofang** [comment]
Done in CuPy v13! Many thanks, @kmaehashi!

**Comment by leofang** [comment]
Please make sure you read the installation guide and don't just do `pip install cupy`.
https://docs.cupy.dev/en/stable/install.html#installing-cupy
