### ISSUE TITLE
Support SciPy 1.11

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7664]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes.
- [x] Fix code and CI to support the new vesrion.
  - **FlexCI**: Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml`. #7897
  - **Update Requirements**: For NumPy/SciPy, bump the pinned minimum/maximum version in `setup.py` (see #4773.) #7992
- [x] Backport the above PR. #7932
- [x] For NumPy update, reflect the changes in `numpy.array_api` to `cupy.array_api`.
- [x] Backport the above PR.
- [x] Fix documentation. #7992
  - Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) (note: the baseline version must be updated only in the development branch).
  - Update `docs/requirements.txt` to use the latest versions.
- [x] Backport the above PR. #8001
- [x] Apply fixes needed to follow the specification changes.

**Comment by asi1024** [comment]
The failure of `tests/cupyx_tests/scipy_tests/sparse_tests/test_base.py` is related to this SciPy update: https://github.com/scipy/scipy/commit/d87d90095e4661aed0613f1a74b7aa1eca5decc2

v1.10.1: https://github.com/scipy/scipy/blob/v1.10.1/scipy/sparse/_base.py#L60
v1.11.3: https://github.com/scipy/scipy/blob/v1.11.3/scipy/sparse/_matrix.py#L4
