### ISSUE TITLE
Support sparse matrix with bool

### ISSUE THREAD

**Issue by asi1024** [cupy/cupy#7741]
Currently, `cupyx.scipy.sparse.*_matrix` classes have partial support for `bool` dtype. Specifically:

* COO matrix does not support `bool` https://github.com/cupy/cupy/blob/eb4a7b4ca9b1caf139abac00845028e6419d51dc/cupyx/scipy/sparse/_coo.py#L141-L144
* Other matrix classes accepts creation of `bool` matrix, but are not well-tested.

```[tasklist]
- [x] Support `bool` matrix in COO #7764
- [ ] Add tests for `bool` dtype for each matrix format
- [ ] Add boolean operators (e.g., `__ne__`) for each matrix format to avoid intermediate conversion to CSR (#7757)
- [ ] Add boolean methods (e.g., `nonzero`) for each matrix format (#7751)
```

**Comment by kmaehashi** [comment]
Compressed matrices (csr_matrix, etc.) support bool.

https://github.com/cupy/cupy/blob/42bf511300cf0f37cc4b312e2b9518486d0e99da/cupyx/scipy/sparse/_compressed.py#L277

**Comment by asi1024** [comment]
@kmaehashi Bool csr_matrix has not been tested, and many tests fail when bool is added to the testing combination.

https://github.com/cupy/cupy/blob/d21f772e5e50198e62275bf70683b2a947191c26/tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py#L136

**Comment by kmaehashi** [comment]
I see, makes sense.

**Comment by kmaehashi** [comment]
@asi1024 FYI - I've rewrote the issue body to use this issue as a tracker.
