### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7899]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes https://docs.python.org/3/whatsnew/3.12.html
- [x] Ask fastrlock to release wheels (e.g., https://github.com/scoder/fastrlock/issues/11)
- [x] Install Python to Windows CI image (ask @kmaehashi)
- [x] Fix code and CI to support the new version. https://github.com/cupy/cupy/pull/7940 https://github.com/cupy/cupy/pull/7947
  - **FlexCI**: Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml` (note: Some Python libraries may not be supported with the newer versions of Python. In that case you should also limit the library version.)
  - **Package Metadata**: Update package classifier and `python_requires` tag (if needed) in `setup.py`.
- [x] Backport the above PR. https://github.com/cupy/cupy/pull/7949 https://github.com/cupy/cupy/pull/7958
- [x] Fix `cupy-release-tools` to support the new version. https://github.com/cupy/cupy-release-tools/pull/368
- [x] Backport the above PR. https://github.com/cupy/cupy-release-tools/pull/370
- [x] Update matrix configuration in cupy-package-builder (*internal tool*)
- [x] Fix documentation. #7947
  - Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html)
- [x] Backport the above PR. https://github.com/cupy/cupy/pull/7958
