### ISSUE TITLE
Support cuTENSOR 2.0

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7983]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes ([cuTENSOR](https://docs.nvidia.com/cuda/cutensor/index.html#changelog) / [cuSPARSELt](https://docs.nvidia.com/cuda/cusparselt/release_notes.html) / [cuDNN](https://docs.nvidia.com/deeplearning/cudnn/release-notes/index.html) / [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html)).
- [ ] Fix code and CI to support the new vesrion.
  - **FlexCI**: Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml`. #7984
  - **Library Installer**: Update `cupyx/tools/install_library.py`. #7997
- [x] ~Backport the above PR.~ No backport to v12.
- [ ] Fix documentation.
  - Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html)
- [x] ~Backport the above PR.~ No backport to v12.
- [ ] Implement new features using the version, if any. #7984

**Comment by leofang** [comment]
cc: @anaruse

**Comment by leofang** [comment]
Done in #7984.

**Comment by leofang** [comment]
Realize there's still one item (docs) on the checklist, reopening... Sorry!
