### ISSUE TITLE
[Tracker] cuSignal non-SciPy compat API porting

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#8055]
This is a tracker issue to port cuSignal's non SciPy-compat API to CuPy before it is added to SciPy. This is based on the fact that the cuSignal repository has already been archived, and we suppose it would be better to make this porting before cuSignal is removed from Rapids suite. This way, existing cuSignal users will not experience inconveniences.

These changes will be merged into CuPy v14, and also backported into CuPy v13. The API will be placed in `cupyx.signal` namespace this time.

- [ ] cusignal.firfilter (emcastillo) #8052
- [ ] cusignal.firfilter_zi (emcastillo) #8052
- [ ] cusignal.firfilter2 (emcastillo) #8052
- [ ] cusignal.read_bin (emcastillo)
- [ ] cusignal.read_sigmf (kmaehashi)
- [ ] cusignal.write_bin (emcastillo)
- [ ] cusignal.write_sigmf (asi1024)
- [ ] cusignal.pulse_compression (takagi) #8039
- [ ] cusignal.pulse_doppler (kmaehashi)
- [ ] cusignal.cfar_alpha (emcastillo)
- [ ] cusignal.mvdr (asi1024)
- [ ] cusignal.freq_shift (takagi)
- [ ] cusignal.real_cepstrum (kmaehashi)
- [ ] cusignal.complex_cepstrum (emcastillo)
- [ ] cusignal.inverse_complex_cepstrum (asi1024)
- [ ] cusignal.minimum_phase (takagi)
- [ ] cusignal.ambgfun (kmaehashi)
- [ ] cusignal.KalmanFilter (emcastillo)
- [ ] cusignal.ca_cfar (asi1024)
- [ ] cusignal.channelize_poly (takagi)
- [ ] cusignal.unpack_bin (kmaehashi)
- [ ] cusignal.pack_bin (emcastillo)
- [ ] cusignal.convolve1d2o (asi1024)
- [ ] cusignal.convolve1d3o (takagi) #8037
