### ISSUE TITLE
CuPy v14 Release Plan

### ISSUE THREAD

**Issue by asi1024** [cupy/cupy#8269]
## Roadmap

```[tasklist]
## Planned Features
- [ ] Support of NumPy 2.0
- [ ] `complex32` support for limited APIs (restart [#4454](https://github.com/cupy/cupy/pull/4454))
- [ ] Support bfloat16
- [ ] Structured Data Type
- [ ] allow using CUDA libraries installed as Python modules [#8013](https://github.com/cupy/cupy/issues/8013)
- [ ] pyproject.toml support
- [ ] Drop support for Python 3.9 following [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html)
```

```[tasklist]
## Timeline & Release Manager
- [ ] **v14.0.0a1** (TBD)
- [ ] **v14.0.0b1** (TBD)
- [ ] **v14.0.0rc1** (TBD)
- [ ] **v14.0.0** (TBD)
```

## Notes

* Starting in the CuPy v13 development cycle, we have adjusted our release frequency to once every two months. Mid-term or hot-fix releases may be provided depending on necessity, such as for new CUDA/Python version support or critical bug fixes.
* The schedule and planned features may be subject to change depending on the progress of the development.
* `v13.x` releases will only contain backported pull-requests (mainly bug-fixes) from the v14 (`main`) branch.

## Past Release Plans

* v9: https://github.com/cupy/cupy/issues/3891
* v10: https://github.com/cupy/cupy/issues/5049
* v11: https://github.com/cupy/cupy/issues/6246
* v12: https://github.com/cupy/cupy/issues/6866
* v13: https://github.com/cupy/cupy/issues/7555

**Comment by jakirkham** [comment]
We should add drop cuDNN bindings to this list

xref: https://github.com/cupy/cupy/issues/8215

cc @kmaehashi @leofang

**Comment by kmaehashi** [comment]
Just a quick update - as now that we see NumPy v2 being widely adopted in the community, and NumPy v1 EoL is approaching (https://endoflife.date/numpy), we are now discussing updating the roadmap to deliver CuPy v14 quickly, which provides APIs equivalent with NumPy v2. More details to be shared on this issue.

**Comment by kmaehashi** [comment]
> Just a quick update - as now that we see NumPy v2 being widely adopted in the community, and NumPy v1 EoL is approaching (https://endoflife.date/numpy), we are now discussing updating the roadmap to deliver CuPy v14 quickly, which provides APIs equivalent with NumPy v2. More details to be shared on this issue.

We've revised the list of features planned for v14 to ensure we can deliver a v14 release as soon as possible. We have (almost) freezed TODO list for v14 in https://github.com/cupy/cupy/milestone/155. Once these items are done we will ship v14.0.0rc1, followed by v14.0.0 stable release.

**Comment by jaredmontoya** [comment]
Build failure:
Nixpkgs commit: `dd9b079222d43e1943b6ebd802f04fd959dc8e61`
Nixpkgs config:
```nix
nixpkgs.config.cudaSupport = true;
```
`nix log /nix/store/48v3jj9v1x2wzvx37q6d53xp72pi6ii9-python3.13-cupy-13.6.0.drv`:
```shell
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pypa-build-hook
Using pypaBuildPhase
Sourcing python-runtime-deps-check-hook
Using pythonRuntimeDepsCheckHook
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
source: sourcing removeStubsFromRunpathHook.bash (hostOffset=-1) (targetOffset=0)
source: added removeStubsFromRunpathHookRegistration to prePhases
Sourcing fix-elf-files.sh
Sourcing fix-elf-files.sh
Running phase: removeStubsFromRunpathHookRegistration
@nix { "action": "setPhase", "phase": "removeStubsFromRunpathHookRegistration" }
removeStubsFromRunpathHookRegistration: added removeStubsFromRunpath to postFixupHooks
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/dc99xz7lfdygqi2kqc7x3hv97jziak0y-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file "source/third_party/jitify/stringify.cpp"
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Updating Autotools / GNU config script to a newer upstream version: ./third_party/cccl/libcudacxx/cmake/config.guess
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
no configure script, doing nothing
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Executing pypaBuildPhase
Creating a wheel...
pypa build flags: --no-isolation --outdir dist/ --wheel
* Getting build dependencies for wheel...
Skipping extensions configuration
running egg_info
creating cupy.egg-info
writing cupy.egg-info/PKG-INFO
writing dependency_links to cupy.egg-info/dependency_links.txt
writing requirements to cupy.egg-info/requires.txt
writing top-level names to cupy.egg-info/top_level.txt
writing manifest file 'cupy.egg-info/SOURCES.txt'
reading manifest file 'cupy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.pxi' under directory 'cupy'
warning: no files found matching '*.hpp' under directory 'cupy_backends'
warning: no previously-included files matching '*.cpp' found under directory 'cupy'
warning: no previously-included files matching '*.cpp' found under directory 'cupyx'
warning: no previously-included files matching '*.cpp' found under directory 'cupy_backends'
adding license file 'LICENSE'
adding license file 'docs/source/license.rst'
writing manifest file 'cupy.egg-info/SOURCES.txt'

ERROR Missing dependencies:
             Cython<3.2,>=3
```

**Comment by seberg** [comment]
Going to close the issue, this is released.  @jaredmontoya this doesn't seem related to this, nor does it look like a CuPy issue at all. The CuPy setup correctly requires Cython, and that is part of a `nix` setup that I don't think is part of CuPy at all.  The `nix` setup needs to be fixed, this is completely expected with `pypa build flags: --no-isolation`

**Comment by jaredmontoya** [comment]
@seberg Oh, sorry. Wrong repo, I thought this issue was part of the nixpkgs repository. My bad 😅
