### ISSUE TITLE
Support NumPy 2.1

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#8514]
## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [ ] Read Release Notes.
- [ ] Fix code and CI to support the new vesrion.
  - **FlexCI**: Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml`.
  - **Update Requirements**: For NumPy/SciPy, bump the pinned minimum/maximum version in `setup.py` (see #4773.)
- [ ] Backport the above PR.
- [ ] For NumPy update, reflect the changes in `numpy.array_api` to `cupy.array_api`.
- [ ] Backport the above PR.
- [ ] Fix documentation.
  - Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html) (note: the baseline version must be updated only in the development branch).
  - Update `docs/requirements.txt` to use the latest versions.
- [ ] Backport the above PR.
- [ ] Apply fixes needed to follow the specification changes.

----

Release notes: https://github.com/numpy/numpy/blob/maintenance/2.1.x/doc/source/release/2.1.0-notes.rst
* New API: `numpy.unstack`
* Deprecation: Passing non-integer inputs as the first argument of bincount is now deprecated
* Expired Dreprecation: Scalars and 0D arrays are disallowed for numpy.nonzero and numpy.ndarray.nonzero.

**Comment by kmaehashi** [comment]
We already covered NumPy v2.1 in our CI a long ago. Closing.
