### ISSUE TITLE
Support Python 3.13

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#8651]
[Python 3.13](https://docs.python.org/3.13/whatsnew/3.13.html) is out. We will likely need to bump to Cython 3.1.0+ to support running under the Free-threaded mode. Ref: https://py-free-threading.github.io/tracking/

## [Tasks](https://github.com/cupy/cupy/wiki/Actions-Needed-for-Dependency-Update)

- [x] Read Release Notes
- [x] Check fastrlock compatibility https://github.com/scoder/fastrlock/issues/20
- [x] Install Python to Windows CI image (ask @kmaehashi)
- [x] Fix code and CI to support the new vesrion. #8953
  - **FlexCI**: Update `.pfnci/schema.yaml` and `.pfnci/matirx.yaml` (note: Some Python libraries may not be supported with the newer versions of Python. In that case you should also limit the library version.)
  - **Package Metadata**: Update package classifier and `python_requires` tag (if needed) in `setup.py`.
- [x] Backport the above PR. https://github.com/cupy/cupy/pull/8974
- [x] Fix `cupy-release-tools` to support the new version. https://github.com/cupy/cupy-release-tools/pull/397
- [x] Backport the above PR. https://github.com/cupy/cupy-release-tools/pull/398
- [x] Update matrix configuration in cupy-package-builder (*internal tool*)
- [x] Fix documentation. https://github.com/cupy/cupy/pull/8986
  - Update Requirements section in the [Installation Guide](https://docs.cupy.dev/en/latest/install.html)
- [x] Backport the above PR.

**Comment by hauntsaninja** [comment]
fastrlock 0.8.3 now supports Python 3.13! Would be nice to just have wheels for Python 3.13 for cupy-cuda (regular build, not free threading)

**Comment by jakirkham** [comment]
As Leo noted, upgrading to Cython 3 will also be needed for Python 3.13 support generally

This because Cython 0.29 lacks Python 3.13 support

xref: https://github.com/cupy/cupy/pull/8457#issuecomment-2564576399
